### ISSUE TITLE
Admin layout adding subsection

### ISSUE THREAD

**Issue by dudewithamood** [gantry/gantry5#1091]
In order to achieve 'row' level styling I've managed to add subsections by editing layout.yaml as follows:

```YAML
layout:
  /header/:
    -
      - custom-2092
  /navigation/:
    -
      - menu-8235
  /main/:
    -
      - system-messages-9961
    -
      -
        row:
          -
            - custom-3113
          -
            - 'custom-3818 50'
            - 'custom-6655 50'
    -
      - custom-2354
  /footer/:
    -
      - custom-7072
  offcanvas:
    -
      - mobile-menu-8911
structure:
  header:
    attributes:
      boxed: ''
      class: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  row:
    title: 'Boxed row'
    type: section
    attributes:
      class: 'g-container'
  main:
    attributes:
      boxed: ''
      class: ''
  footer:
    attributes:
      boxed: '0'
      class: ''
```
In admin layout this looks like this:
![image](https://cloud.githubusercontent.com/assets/15866807/12018328/e4888a82-ad69-11e5-9097-7d5ea1b6641a.png)

So my feature request is to be able to select what to add when the '+' is clicked for a section, where subsection is one of the options, so I can achieve the above from the admin layout screen without having to manually edit layout.yaml. Currently it adds a row (grid element) that cannot have a class attached (although grid.html.twig appears to cater for it).

Thank you :-)
