### ISSUE TITLE
gantry 5, customization in section (img background repeat)

### ISSUE THREAD

**Issue by astenio** [gantry/gantry5#1268]
I use 'gantry 5 framework' in wordpress, I created a customization for all sections where it is possible to enable an image to backgroun in any section of the template layout, but I would like to improve, I wish it was possible to select the characteristics of the cSS for the image background as: no-repeat, repeat-x, repeat-y, or repeat-xy, that in a dropdown. Does anyone know show me a tutorial, how to build this solution?

**Comment by newkind** [comment]
Hi,

You need to create (or edit existing) yaml file in the blueprints directory `themes/rt_hydrogen/blueprints/styles/header.yaml` and add a select field to this file ie.

```
backgroundrepeat:
  type: select.select
  label: Background Repeat
  default: norepeat
  options:
    norepeat: 'no-repeat'
    repeatx: 'repeat-x'
    repeaty: 'repeat-y'
    repeatxy: 'repeat-xy'
```

After that you should be able to use the `$header-backgroundrepeat` (header word comes from the yaml filename) variable in the SCSS files ie.

```
#g-header {
  background: $header-background;
  background-repeat: $header-backgroundrepeat;
}
```

More about YAML files : http://docs.gantry.org/gantry5/advanced/particle-yaml-field-types
