### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by dpwysicj** [gantry/gantry5#1274]
I am running Joomla 3.5 in xampp and gantry5. I created a custom css file in "templates\g5-hydrogen\custom\scss\custom.css. The problems are:

1.  "color" works on class', "leadverse", "verse", "ref" but not on "p" or "blockquote"

2.  "blockquote" is picking up "textalign: justify;" from "p". There are no "p" in "blockquote".

I have not tested further. Any help would be appreciated.

```css
p {
    text-align: justify;
    text-indent: 10px;
    color: #0f0d72;
}
.noindent {
    text-indent: 0px;
}
ul ol {
    margin-left: 20px; 
}
li {
    margin-right: 5px;
    margin-bottom: 7px;
}
.leadverse {
	font-weight: bold;
	text-align: justify;
	color: Maroon;
	margin: 0px 20% 10px 20%;
	text-indent: 0px;
}
.verse {
	margin: 0px 10% 10px 10%;
	text-indent: 0px;
        text-align: justify;
	text-indent: 0px;
       color: #0f0d72;
}
.ref {
      font-style: italic;
      text-align: center;
      font-size: small;
      color: #0f0d72;
}
blockquote {
	margin-right: 1.5em;
	margin-left: 1.5em;
    	color: #0f0d72;
	text-indent: 0px;
}
```
