### ISSUE TITLE
Custom Root for Type: input.imagepicker and input.filepicker

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#1305]
There is a bug when we would use these as root, custom folder and gantry-theme:// or gantry-media://

```
image:
      type: input.imagepicker
      label: Image
      description: Select the main image.
      root:
        - test
        - gantry-theme://
        - gantry-media://
```

![2016-05-23 21 27 02](https://cloud.githubusercontent.com/assets/10489911/15482826/f48239d8-2131-11e6-8d16-b588fdc10fe1.jpg)
