### ISSUE TITLE
"Joomla Article" particle not translating dates to correct language

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#1322]
The "Joomla Article" particle only appears to be able to show English language dates (in frontend or backend) despite the default language being changed. 

This particle should show dates in the language being used.

Forum link: http://www.rockettheme.com/forum/joomla-template-topaz/259402-date-language-in-gantry-5-particle-on-showcase-b?start=0#1296022

**Comment by w00fz** [comment]
This seems somewhat related to #221

**Comment by mahagr** [comment]
Just an update: Particle has date format set by user so it won't be translated because of that.

**Comment by mahagr** [comment]
CC @JoomFX

**Comment by marktaylor46** [comment]
@mahagr can you explain a bit further please. The use installed a non-english language and set it as the default language - it is the particle that shows the published date (via joomla calls) - so how would the user ever be able to get anything other than english date formats? Is there a setting somewhere else?

**Comment by JoomFX** [comment]
@mahagr Can't the format dates be translated?

If I remove the format option, then the date is shown like this - `2016-06-13 11:44:16`

As @w00fz suggested in the other issue, maybe the [Intl Extension](http://twig.sensiolabs.org/doc/extensions/intl.html) is the way to go?

**Comment by marktaylor46** [comment]
I agree... a better solution is required here... this particle needs to show the dates in the correct language.

**Comment by mahagr** [comment]
Intl Extension doesn't work as most servers do not have it installed. I agree that we need a solution, but not sure what it could be as the solution really depends on the platform too.

**Comment by JoomFX** [comment]
@mahagr In the other issue you said that something similar was added to Grav.
Maybe it can be brought to G5 as well?

**Comment by Vanguger** [comment]
Example: date Joomla System - 

file: templates/G5_TEMPLATE/custom/particles/date.yaml - 

```
name: Date
description: Display a date.
type: particle
icon: fa-calendar

form:
  fields:
    enabled:
      type: input.checkbox
      label: Enabled
      description: Globally enable date particles.
      default: true

    css.class:
      type: input.selectize
      label: CSS Classes
      description: CSS class name for the particle.
      default: date

    date.formats:
      type: select.date
      label: Format
      description: Select preferred date format.
      default: j F Y
      placeholder: 'Select...'
      selectize:
          allowEmptyOption: true
      options:
          'F Y': Date1
          'j F Y': Date2
```

file: templates/G5_TEMPLATE/custom/particles/date.html.twig - 

```
{% extends '@nucleus/partials/particle.html.twig' %}

{% block particle %}

	{% set ln = ['','JANUARY','FEBRUARY','MARCH','APRIL','MAY','JUNE','JULY','AUGUST','SEPTEMBER','OCTOBER','NOVEMBER','DECEMBER'] %}

	{% set d = "now"|date("j") %}
	{% set m = "now"|date("n") %}
	{% set y = "now"|date("Y") %}
	{% set s = ln[m]|trans %}
	{% set f = particle.date.formats %}

	{% if f == 'F Y' %}{% set dt = s~" "~y %}{% endif %}
	{% if f == 'j F Y' %}{% set dt = d~" "~s~" "~y %}{% endif %}

    <div class="g-date">
        <span> {{ dt }}  </span>
    </div>

{% endblock %}
```
