### ISSUE TITLE
"collection.list" in "container.set" not working

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#1333]
Guys, I'm trying to group different fields in a particle with `container.set`.
But when I put `collection.list` in a `container.set`, the items do not work. The items are created, but when you click on the item to open it you get "404 Not Found".

Here's a quick YAML code to test with:

```
    something:
      type: container.set
      label: Something
      fields:
        .items:
          type: collection.list
          array: true
          label: Something Items
          description: Create each item to display.
          value: name
          ajax: true

          fields:

            .icon:
              type: input.icon
              label: Icon

            .value:
              type: input.text
              label: Value
```
