### ISSUE TITLE
Add labels variations colors

### ISSUE THREAD

**Issue by 810** [gantry/gantry5#1471]
See: http://getbootstrap.com/components/#labels

**Comment by 810** [comment]
ok, the colors are there, but there are overwritten by the 
```Css
.label-info, .badge-info {
    background: #fff;
}
```
