### ISSUE TITLE
Semantic HTML Improvements

### ISSUE THREAD

**Issue by coder4life** [gantry/gantry5#1485]
Gantry does a great job with rendering sections with the appropriate markup, however there is a bit of control behavior that can be undesired when trying to make semantic improvements.

As per discussion with @mahagr it was figured that under the **structure** key under the YAML and the various settings should properly respect the subtype even if it is not a **section**. As this is an explicit action from the template designer it makes sense to support this behavior.

```yaml
structure:
  container-main:
    subtype: main
    title: Main
    block:
      fixed: 1

  sidebar:
    subtype: aside
    block:
      fixed: 1
```
