### ISSUE TITLE
JS warning notification title not translating

### ISSUE THREAD

**Issue by nikola3244** [gantry/gantry5#1525]
If a field has an invalid value and you click "Appy", a warning shows up with the title  `GANTRY5_PLATFORM_JS_INVALID_FIELDS`

**Comment by w00fz** [comment]
Are you sure the lang file has been copied over properly during installation?

**Comment by nikola3244** [comment]
I'm pretty sure. That's the only missing string so far. How can I check?

**Comment by mahagr** [comment]
I just checked that the key gets translated and is specified in `js-translations.html.twig`. Not sure why it doesn't work.

**Comment by w00fz** [comment]
I think this is related to your install, I'm quite positive the lang files haven't been replaced properly during installation. I'd try to copy them manually.

These are the locations:

1. Wordpress: `wp-content/plugins/gantry5/admin/languages/gantry5-en_US.[po|mo]`
2. Joomla: `administrator/components/com_gantry5/language/en-GB/en-GB.com_gantry5.ini`

I tried both Joomla and Wordpress and I get the proper translation:

![gantry 5 dev - administration 2016-08-29 16-26-28](https://cloud.githubusercontent.com/assets/11734/18070838/88cf1f78-6e05-11e6-9f1d-e3277e852dce.png)

I'm going to close this as I can't reproduce but if you see something odd please feel free to reopen.

Cheers!

**Comment by nikola3244** [comment]
@w00fz You are right, message does work!
But only in layout manager.

Try to input "0.1" in this atom and click save:
```
name: Test
description: 
type: atom
icon: fa-exchange

form:
  fields:
    enabled:
      type: input.checkbox
      label: Enabled
      description: Globally enable it.
      default: true

    test:
      type: input.number
      label: Test
      description: Test
```

Btw, I tried to redownload .mo, but it's still not working.
