### ISSUE TITLE
contentarray particle only retrieves post categories

### ISSUE THREAD

**Issue by dudewithamood** [gantry/gantry5#1535]
Hi, in Wordpress, the categories field used in contentarray only fetches post categories.

For the posts field I am able to specify in a particle's yaml to return post-type: any but I don't seem to be able to make any such adjustment for the categories field.

Please advise.

**Comment by newkind** [comment]
You mean that you want a selectize field that would return all custom post types ?

**Comment by dudewithamood** [comment]
All taxonomies for posts and custom post types.

So for example, I'm using a modified version of the contentarray particle that has both the categories and posts field. I can either choose to display posts from a category using the categories field, or I can individually select the posts I want from the posts field.

Currently, if I want to show posts (products) from a WooCommerce product category I have to use my second option and individually select them (which I can do because for the posts field I specify in the particle's yaml to return post-type: any). I can't select the product category from the categories field as is only shows post categories.

These are my field settings:
```
post.filter.posts:
  type: wordpress.posts
  label: Posts
  description: Individually select posts to display.
  post_type: any

post.filter.categories:
  type: wordpress.categories
  label: Categories
  description: Select categories to show posts from.
```

**Comment by adi8i** [comment]
It's not gonna play well like this. I think content array particle was coded with wordpress content in mind, woocommerece is 3rd party, and it have custom fields. Same apply to any 3rd party.

**Comment by dudewithamood** [comment]
This stretched me out of my comfort zone to look at it more closely and see if it could be done the same way as get_posts... but I see you've started working on it in #1546

While WooCommerce is 3rd party it uses the standard Wordpress taxonomy system. The code I shared in #1546 is pulling WooCommerce categories (in addition to post categories and any other custom taxonomy entries I've created)

**Comment by adi8i** [comment]
You can chose categories to be pulled.
```
    categories:
      type: wordpress.categories
      label: Categories 
      taxonomy: any-taxonomy
```

You can send a PR at any time. Peeps have different ideas.
