### ISSUE TITLE
Homepage broken after upgrade to G5.3.5 using Requiem template

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#1548]
I just updated a site that is using the Requiem template to G5.3.5. This site is a multilingual site. On reloading the home page, I noticed that the home page CSS and Styles were not being applied.

I looked in the inspector to see what the differences were between the pre- and post update generated code:

The first thing I noticed was that the home page body tag no longer had the class `g-homepositions`.

![woodyway_-_home](https://cloud.githubusercontent.com/assets/1498512/18224739/242c980a-71e0-11e6-803c-23a080ba5daa.jpg)

I went to the administrator backend and loaded the Gantry 5 component and looked at the outlines. Everything seemed to be OK.

In the layout manager of the outline, it still says **Layout** (Home Positions).

But the site isn't showing the home positions in the front end.

**Comment by alisamii** [comment]
The problem seems to be associated specifically with **Requiem-based** sites and the **Regular Labs Advanced Template Manager v2.1.1**. I have the **Advanced Template Manager v2.1.1** installed on an **Isotope-based** template with no problems. But updating the **Requiem-based** site with **Advanced Template Manager v2.1.1** breaks the site.

**Comment by mahagr** [comment]
Check the outline 29, that's what is used to display the page. It also looks like its using default layout instead of home positions. Outline (or template style) is picked up by Joomla, or in this case ATM, so the question is why it fails?

**Comment by alisamii** [comment]
@mahagr Here is what I find in Outline 29:

in `index.yaml`
```
name: 29
timestamp: 1473067108
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1457608748
```
in `layout.yaml`
```
version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1457608748
layout:
  top: {  }
  navigation: {  }
  header: {  }
```

Just the start of the files, obviously.

Looking in the g5 admin backend, according to the Outlines Manager and Layout Manager:
Outline 29 is `Requiem - Default - ALL` and uses the `Default` Preset. It is set to Default.
Outline 40 is `Requiem - Default - EN` and uses the `Default` Preset. It is set to Default.
Outline 41 is `Requiem - Default - EN` and uses the `Default` Preset. It is set to Default.
Outline 30 is `Requiem - Home - EN` and uses the `Home Positions` Preset.
Outline 39 is `Requiem - Home - FR` and uses the `Home Positions` Preset.

So, I'm unsure what the issue is.
