### ISSUE TITLE
Dependant fields

### ISSUE THREAD

**Issue by dudewithamood** [gantry/gantry5#1572]
Feature request for fields (and tabs) that show dependent on selections in other fields.

For example, if there is a tab for featured image with various settings that control how the image is displayed, and a separate select field where I can choose to display image or not, it would be nice if that tab would display or not depending on the option selected.

The YAML could look something like this (note the **depends** addition) where selecting Yes for Show image would display the Image tab and selecting No would hide it:
```
...
display.image:
  type: select.select
  label: Show image
  default: true
  options:
    true: Yes
    false: No

_tabs:
  type: container.tabs
  fields:
    _tab_image:
      label: Image
      depends:
        display.image: true
      fields: ...
```
... and similarly with fields...
```
...
post.display.read_more.enabled:
  type: input.checkbox
  label: Read More
  default: true

post.display.read_more.label:
  type: input.text
  label: Read More Label
  depends:
    post.display.read_more.enabled: true
...
```
