### ISSUE TITLE
Joomla: abilty to load print.css or disable default print style

### ISSUE THREAD

**Issue by Chrissi2812** [gantry/gantry5#1598]
An option to load a print.css like the custom.css would be great.
```html
<link rel="stylesheet" type="text/css" media="print" href="templates/hydrogen/custom/print.css">
```
The hydrogen.css and the custom.css should then be loaded like this:
```html
<link rel="stylesheet" type="text/css" media="screen" href="templates/hydrogen/custom/hydrogen.css">
<link rel="stylesheet" type="text/css" media="screen" href="templates/hydrogen/custom/custom.css">
```
Alternatively a switch to disable the default print styling would help to style in some situations where you have inline styles.

**Comment by mahagr** [comment]
You can already add CSS for printing, just use Page Settings tab to add the CSS file and use `Tag Attributes`: `media` -> `print` to specify style for printing.

What comes to the another part, @w00fz @hexplor @newkind ?

**Comment by Chrissi2812** [comment]
Okay thats a good starting point :)
But would it be hard to integrate this automatic behaviour from the custom.scss for a print.scss? 

This is code causes some issues:
```css
/*bootstrap-gantry.css*/
@media print {
	* {
		color: #000 !important;
		text-shadow: none !important;
		background: transparent !important;
		box-shadow: none !important;
	}
	...
}
```
This overrides all inline background-images (we use them as replacement for object-fit witch isn't supported in IE).
