### ISSUE TITLE
Gantry should overide Menu CSS not replace it

### ISSUE THREAD

**Issue by shoulders** [gantry/gantry5#1656]
This issue might not affect every one but i will outline it using the forum link as an example

1. i was running a joomlashine template in which i added font awesome icon to the menu item via the joomla menu item's 'Link CSS Style' and added 'fa fa-users'
![with forum icon](https://cloud.githubusercontent.com/assets/319997/19965671/10952cde-a1c0-11e6-8dd5-fb293fae6863.jpg)

2. I installed gantry and set the main-menu in settings to be used.

3. i then edited the main menu via Gantry by adding an icon. This worked fine, the icon changed.
![gantry icon settings](https://cloud.githubusercontent.com/assets/319997/19965752/5fdf81ae-a1c0-11e6-9ee6-dc73f217f852.jpg)

![with new icon](https://cloud.githubusercontent.com/assets/319997/19965705/3a2dc6fa-a1c0-11e6-8bc4-e283a4d5f697.jpg)

4. i decided i did not like the icon and preferred the old one so i removed the icon in gantry, but the icon did not revert back to the old icon but in fact no icon was then left.
![no icon](https://cloud.githubusercontent.com/assets/319997/19965715/40d4051e-a1c0-11e6-8c01-5413c19230c4.jpg)

Looking at this issue, what happens is when you make an alteration to the menu like adding an icon, these changes are stored in the /custom/config/menu/mainmenu.yaml and when you delete the icon, the icon value is removed but the rest of the item remain. Is this causing Gantry to use only it's menu styling for this item and ignore the joomla one from now on.

**With Icon code**
```yaml
ordering:
  home: ''
  blog: ''
  software: ''
  2016-09-30-17-17-00: ''
  kb:
    articles: ''
    links: ''
    videos: ''
  stuff:
    links: ''
    videos: ''
  search: ''
items:
  2016-09-30-17-17-00:
    id: 745
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
    icon: 'fa fa-anchor'
```

**Without Icon code**
```yaml
ordering:
  home: ''
  blog: ''
  software: ''
  2016-09-30-17-17-00: ''
  kb:
    articles: ''
    links: ''
    videos: ''
  stuff:
    links: ''
    videos: ''
  search: ''
items:
  2016-09-30-17-17-00:
    id: 745
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
```

**NB:** above it shows a date rather than the name forum I think because it is a menu alias.

I would recommend that the stying from gantry CSS overrides those that are set in the joomla menu item to keep things working as expected. If you remove the icon styling from gantry and there is still an icon this is easier to understand than the icon is still syled in joomla but not shown. I cannot see a way of fixing this for the end user. Also there might be other styles that the user wants to use not just font awesome icons but other joomla plugins that need these CSS classes to be present.

Thanks
