### ISSUE TITLE
limit number of google analytics and custom css/js atoms per layout?

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#166]
i know this is not a reasonable thing to try, but i did anyways. :)

it seems you can use the google analytics and custom css/js atom several times within the layout, maybe once they have been added to the layout, they should be 'greyed out' / deactivated on the left side? please see pic.

![g5_gacustom-1](https://cloud.githubusercontent.com/assets/5719486/7426409/1e9456a0-ef8a-11e4-9ef6-b9f25f2e0589.jpg)

**Comment by mahagr** [comment]
And what if you have legit reason to have multiple instances in there? I was thinking that in the future we might want to have multiple instances from Custom CSS/JS where some of them may be shared between many configurations.

**Comment by Omegatcu** [comment]
I think this makes only sense if we have something like a field we can define in the yaml.

Like:
```yaml
form:
  count: 1
  fields:
    enabled:
      type: input.checkbox
      label: Enabled
      description: Globally enable the atom.
      default: true
```
but i don't really know if it is worth the time right now.
