### ISSUE TITLE
add content block spacing variables to gantry admin

### ISSUE THREAD

**Issue by shoulders** [gantry/gantry5#1675]
Feature request: can you add the ability to set the Content Block Spacing Variables in the gantry admin.

This came about because i wanted to reduce the spacing between all sections and I found there was not a setting in gantry admin for this. 

I can just override the _core.scss but i think this would be better to alter this setting in the admin.

**What I did / tried**

This files controls those settings /g5_helium/scss/configuration/_core.scss

````// Content Block Spacing Variables
$content-margin:			0.625rem !default;
$content-padding:			0.938rem !default;

$section-padding:			3rem;
$core-border-radius:		0.25rem;
$border-radius:				0.25rem;
````

I wrote an override gantry admin yaml /g5_helium/custom/blueprints/styles/core.yaml

````
name: Content Block Spacing
description: Core Content Block Spacing Variables
type: core

form:
  fields:

    content-margin-input:
      type: input.text
      label: Content Margin
      description: Set breakpoint size in rem, em, or px unit values
      default: "0.625rem"
      pattern: '\d+(\.\d+){0,1}(rem|em|ex|ch|vw|vh|vmin|vmax|%|px|cm|mm|in|pt|pc)'
    content-padding-input:
      type: input.text
      label: Content Padding
      description: Set breakpoint size in rem, em, or px unit values
      default: "0.938rem"
      pattern: '\d+(\.\d+){0,1}(rem|em|ex|ch|vw|vh|vmin|vmax|%|px|cm|mm|in|pt|pc)'
      
    section-padding-input:
      type: input.text
      label: Section Padding
      description: Set breakpoint size in rem, em, or px unit values
      default: "3rem"
      pattern: '\d+(\.\d+){0,1}(rem|em|ex|ch|vw|vh|vmin|vmax|%|px|cm|mm|in|pt|pc)'
    
    core-border-radius-input:
      type: input.text
      label: Border Radius
      description: Set breakpoint size in rem, em, or px unit values
      default: "0.25rem"
      pattern: '\d+(\.\d+){0,1}(rem|em|ex|ch|vw|vh|vmin|vmax|%|px|cm|mm|in|pt|pc)'    
    border-radius-input:
      type: input.text
      label: Border Radius
      description: Set breakpoint size in rem, em, or px unit values
      default: "0.25rem"
      pattern: '\d+(\.\d+){0,1}(rem|em|ex|ch|vw|vh|vmin|vmax|%|px|cm|mm|in|pt|pc)'
````

and a corresponding SCSS file /g5_helium/custom/scss/configuration/_core.scss

````
// Content Block Spacing Variables
$content-margin:			$content-margin-input !default;
$content-padding:			$content-padding-input !default;

$section-padding:			$section-padding-input;
$core-border-radius:   	        $core-border-radius-input;
$border-radius:				$border-radius-input;

````

The admin section apperars and the _core.scss is overridden but the values from the admin do not get translated into the css.

As you can see I tried the basic matching variables but it does not work

````$content-margin:			$content-margin-input !default;````
