### ISSUE TITLE
[ContentArray][Grav] Several features doesn't work

### ISSUE THREAD

**Issue by hexplor** [gantry/gantry5#1699]
I did a qucik test for content array particle in grav and several things does not appear to work:

- [x] Order by
- [x] Sort Order
- [x] Start From
- [x] Article Image (I think we don't have something like that in grav)
- [x] Article Text: Introduction (the same, we don't have something like that in grav) 
- [x] Title limit returns html symbols: https://monosnap.com/file/T6bJpk7OrSx2OfcoWQoyfopPUV2rGm.png, 
- [x] Author

**Comment by mahagr** [comment]
@hexplor 

You can use `===` in Grav for page summary separator.

**Comment by mahagr** [comment]
Added support for summary and text images (defaulting to the first image for the page).

Also added author field..

```yaml
author: John Snow
image:
    summary:
        file: snow-summary.jpg
    text:
        file: snow.jpg
```
