### ISSUE TITLE
GANTRY and GRAV page collection

### ISSUE THREAD

**Issue by oscon** [gantry/gantry5#1779]
I'm trying to build a BLOG website with GRAV, GANTRY and the helium theme. Unfortunately it seems as if the GRAV Page Collection does not work with the Page Content page: No BLOG entries are displayed. Do I have to adapt the helium theme anyway?
The Page Collection is configured as follows:

```yaml
title: Blog
blog_url: blog
body_classes: 'header-image fullwidth'
sitemap:
    changefreq: monthly
    priority: 1.03
content:
    items: '@self.children'
    order:
        by: date
        dir: desc
    limit: 1
    pagination: true
feed:
    description: 'Sample Blog Description'
    limit: 10
pagination: true
```

![2017-01-04 17_59_12-blog _ grav](https://cloud.githubusercontent.com/assets/478932/21651274/4a50c15e-d2a8-11e6-9250-c5e68e0cfa23.png)
