### ISSUE TITLE
GRAV : Protean Theme - Flipster Particle

### ISSUE THREAD

**Issue by OptikWebCreative** [gantry/gantry5#1781]
Hi Team

Can we please change the input type on the following in flipster.yaml
```
    spacing:
      type: input.number
      label: Spacing
      description:  Space between items relative to each item's width. 0 for no spacing, negative values to overlap.
      default: -0.6
```

to

```
    spacing:
      type: input.text
      label: Spacing
      description:  Space between items relative to each item's width. 0 for no spacing, negative values to overlap.
      default: -0.6
```
