### ISSUE TITLE
"overridable" is broken, it doesn't work with all field types

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#1818]
```
name: AI Test
description:
type: particle

form:
  fields:
    enabled:
      type: input.checkbox
      label: Enabled
      description: Globally enable the particle.
      default: true

    number:
      type: input.number 
      label: Number 
      overridable: false

    select:
      type: select.select 
      label: Select 
      overridable: false
      default: value 
      options:
        value: Value
```

![capture](https://cloud.githubusercontent.com/assets/9744973/22176905/7dec3b52-e01c-11e6-8d5d-9033958079a3.PNG)

**Comment by mahagr** [comment]
I'm not able to reproduce this issue; none of the fields are visible on my test sites.

**Comment by mahagr** [comment]
I may know what's going on in your site.

If you set a value to the field and only after that change it not to show up in defaults, it will force the field to show up. This is because of you may be still using the value somewhere and hiding the field would reset the value and potentially break your particle instances.

**Comment by adi8i** [comment]
Hi, sorry Matias I don't fully understand ,so you mean that I configured the particle, then I edited the yaml file to add the `overridable` parameter, but is not the case here.

The following filed is displayed in `Particle Defaults` but it's not configured. Or I misunderstand it's use... 
```
    columns:
      type: input.number
      label: Columns
      overridable: false
      default: 3
      min: 1
      max: 6
      required: true
```
