### ISSUE TITLE
CSS not loading properly when added as a file in Page Settings as a CSS Asset.

### ISSUE THREAD

**Issue by N8Solutions** [gantry/gantry5#1829]
This comes on the heels of the latest release of v5.4.6.

I have been working on adding a video as a background to the showcase section.
The code for this works if you add it or import it to the **custom.scss** file. I can specify it to load only for a single outline using it's ID# but that still loads the code globally in the template which isn't needed as it is only for a single outline. I know it could also theoretically be done by creating a particle and adding it that way but I have not gone that route and it still doesn't address the issue.

**Before** the release of v5.4.6, with the prior latest CI build, the code when loaded under page settings as a **css asset** or as a **custom css/js atom** did not load properly.

**After** the release of v5.4.6 the code loads properly when loaded as a **custom css/js atom** but the problem remains when it is loaded as a **css asset**.

I worked up 3 different scenarios on a test site where each menu item was given it's own outline for testing purposes.
http://hydrogen.rt.n8solutions.org/hydro

**Home 1 (working)** - The code is imported to the custom.scss file and nothing else is in the custom.scss file. Everything works perfectly as expected. I did force it to load only for the Home 1 outline by specifying it's ID. Other than that the code for the other pages is the exact same
**Home 2 (not working)** - The code is added as a **css asset** with priority 10.
**Home 3 (working)** - The code is added as a **custom css/js atom** with priority 10.

Dev's, if you want admin credentials for the site please let me know  via PM and I'll send them to you.

@mahagr This is the same issue we were discussing. The only thing I did to the code after speaking with you was to change the `z-index` from `-100` to `0`.
@w00fz I know you said previous versions didn't load sass properly when loaded as a as a **css asset** or as a **custom css/js atom** but since Matias has added that feature the code I'm trying to add should work properly.

If I am wrong about this or if there is a problem with the code I'm using please let me know.
### CUSTOM.SCSS
```css
@import "dependencies";
@import "home";
```

### _HOME.SCSS
```css
.outline-13 {
	#g-header {
		background-color: rgb(194, 63, 45);
		background-image: linear-gradient(to bottom, rgb(194, 63, 45), rgb(71, 25, 25));
		background-repeat: repeat-x;	
	}
	#g-navigation {
		background-color: rgba(27, 27, 27, 0);
		background-image: linear-gradient(to bottom, rgba(27, 27, 27, 0.2), rgba(27, 27, 27, 0.7));
		background-repeat: repeat-x;
		border-bottom: 1px solid #000000;
		box-shadow: 0 2px 4px rgba(0, 0, 0, 0.3), 0 -1px 1px rgba(225, 225, 225, 0.3) inset;
		color: #dddddd;
	}

	/* Video CSS for background image */
	/* IE8 <video> interpretation as block */
	video {display: block;}

	#g-showcase {
		position: relative;
		background: none; /* Hides the default background image and color for the Showcase section */
		min-height: 70vh;
		video#bgvid {
			position: absolute;
			right: 0;
			bottom: 0;
			min-width: 100%;
			min-height: 100%;
			width: auto;
			height: auto;
			z-index: 0;
			background: url(gantry-media://videos/Cassandra_copyrightdownloopscom.jpg) no-repeat;
			background-size: cover;
		}
	}

	.n8-showcase-text {
		background-color: rgba(0, 0, 0, 0.5);
		border: 1px solid #000000;
		border-radius: 8px;
		box-shadow: 0 0 1px rgba(225, 225, 225, 0.8) inset;
		color: #ebebeb;
		text-shadow: 1px 1px 1px rgba(0, 0, 0, 0.5);
	}
}
```

### HOME2.SCSS 
This file is used on the site for loading the code as both a  **css asset** and as a **custom css/js atom**.
It contains the exact same code as the **_home.scss** file except for that the code is not wrapped in the `.outline-13` class. When you visit the site you'll see that the contents of the **Showcase** section are behind the video for **Home 2** (not correct) but with the same file loaded as a **custom css/js atom** for **Home 3** the contents sit on top of the video showing that the code was loaded properly.
