### ISSUE TITLE
Collection is not working if the field selector is nested: main.items

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#1867]
You can create items, but you can't edit the item, error 404

```
main.items:
  type: collection.list 
  label: Items 
  array: true 
  ajax: true 
  value: name 
  fields:
    .title:
      type: input.text 
      label: Title
```
