### ISSUE TITLE
Nested collection.list items cannot be accessed/edited after upgrading to 5.4.7 or 5.4.8

### ISSUE THREAD

**Issue by nicutor** [gantry/gantry5#1877]
Hi,

After upgrading to 5.4.7 from 5.4.6 I cannot access/edit the items from nested collection.list.

Example:

collection.list 1 - I can see the items and click/edit them
collection.list 2 (nested) - I can see the items. Why I click on the items it redirects me to "collection.list 2" main window. 

If you cannot reproduce it, I will create a test particle for you.

All of these collection.lists are under a tab of container.tabs.

Upgrading to 4.5.8 is not fixing this.

Thank you.

**Comment by mahagr** [comment]
Can you provide me an example to save my time? :)

**Comment by nicutor** [comment]
I've sent you a private message with URLs for samples

Let me know if anything else is needed.

Thanks

**Comment by adi8i** [comment]
There are 2 issues in latest CI.

1. Edit all items, will edit only one item
2. With nested collection the wrong modal is opened. If you have items collection and subitem collection within items, edit subitem will open the item modal.

```
name: Nested Collection
description:
type: particle

form:
  fields:
    enabled:
      type: input.checkbox
      label: Enabled
      description: Globally enable the particle.
      default: true
    
    items:
      type: collection.list 
      label: Items 
      array: true
      ajax: true 
      value: name 
      fields:
        
        .text:
          type: input.text
        
        .subitems:
          type: collecton.list
          label: Subitems  
          array: true 
          ajax: true 
          value: name 
          fields:
            
            .text1:
              type: input.text 
              label: Text 1
```
