### ISSUE TITLE
nested collection within tabs, wrong modal opens

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#1882]
With the following example, if you edit a `subitem`, the `item` modal will be opened.
```
name: Test
description:
type: particle

form:
  fields:
    enabled:
      type: input.checkbox
      label: Enabled
      description: Globally enable icon menu particles.
      default: true
    
    _tabs:
      type: container.tabs 
      fields:
        
        _tab_main:
          label: Main
          fields:
            
            items:
              type: collection.list 
              label: Items 
              array: true 
              ajax: true 
              value: name 
              fields:
                
                .test:
                  type: input.text 
                  label: Test 
                
                .subitems:
                  type: collection.list 
                  label: Subitems 
                  array: true 
                  ajax: true 
                  value: name 
                  fields:
                    
                    .test1:
                      type: input.text 
                      label: Test 1
```
