### ISSUE TITLE
imagepicker URL

### ISSUE THREAD

**Issue by butchewing** [gantry/gantry5#1943]
I have a particle that uses the Gantry imagepicker. Everything is working perfectly. However, I am needed to resize the image on template. I see that imagepicker reutrns `url('{$url}')`

yaml
```
fields:
        .image:
          type: input.imagepicker
          label: Image
          description: Select an image.
```

html.twig
```
<img src="{{ item.image }}">
```

I assume that since Gantry returns the gantry-media:// URL, that I am not able to utilize the Grav Media methods like Crop Resize.

I would like to do something like the following:
```
{{ item.image.cropResize(300, 300).html() }}
```

I have tried wrapping it in url()
```
<img src="{{ url(item.image1) }}">
```

```
{{ item[url(item.image1)].cropResize(300, 300).html() }}
```

**Comment by mahagr** [comment]
Sorry about the delay.

Grav methods should work, but not directly to the variable. Try something like 

```twig
{{ page.media[item.image].cropResize(300, 300).html()|raw }}
```

**Comment by mahagr** [comment]
I'm assuming that the question got answered.

**Comment by thekenshow** [comment]
I'm running into this problem and item.image doesn't seem to resolve it. Example:
```
		{% for tabimage in mod.header.tabimages %}
		<div class="g-block">
			<div class="g-content">
				{% if tabimage.image %}
				<div class="g-tab-image">
                                        {# The following lines work as expected #}

					{% set thisimg = modurl ~ '\/' ~ tabimage.image %}
					<img src="{{ url(thisimg)|e }}" alt="{{ tabimage.title|e }}" />

                                         {# The following line returns an image item filename,, e.g., leflar_white-on-gray_400sq.png #}
					
                                         {{{ tabimage.image|raw }}

                                         {# The following 3 lines return nothing, using tabimage.image item or image item filename #}
					
                                         {{ grav.page.media[tabimage.image].resize(400, 200).html()|raw }}

					{{ grav.page.media["leflar_white-on-gray_400sq.png"].resize(400, 200).html()|raw }}

                                         {{ grav.page.media['leflar_white-on-gray_400sq.png'].url|raw }}					

				</div>
				{% endif %}	
		        </div>
		</div>
		{% endfor %}
```

**Comment by mahagr** [comment]
It's likely tat the page doesn't have the image. What's in `modurl`?

**Comment by thekenshow** [comment]
The pages does have the image and it renders correctly using url(). 

The `modurl` variable contains the full path of the modular page that holds the image. This Twig is in a particle with a field that specifies just the module name. The particle assumes a module of the modular page being rendered.

```
{% set modparent = grav.page.route %}

{% if (modparent == "\/") %}
	{% set modparent = grav.config.system.home.alias %} // need the full path for the page.find later
{% endif %}

{# Get configured module folder name #}
{% set modfolder = particle.modslug %} // the modular path as configured in the particle
{% set mfexists = true %}
{% if not modfolder|defined %}
<div class="alert alert-warning center">
  {% set mfexists = false %}
  <p><em>No module name specified.</em></p>
</div>
{% endif %}

{% if (modfolder|first != '_' ) %} // check if the particle field value left out the underscore
{% set modfolder = '_' ~ modfolder %}
{% endif %}

{# Get the targeted module #}
{% set modurl = modparent ~ '\/' ~ modfolder %}  // get the full path of the modular
{% set mod = grav.page.find( modurl ) %}
```
In this case, that modular is below the home page, so `modurl` contains `home/_partners` Here's the code with the url() approach included:

```
{% set thisimg = modurl ~ '\/' ~ tabimage.image %}

{{ tabimage.image|raw }} // this displays the image file name, leflar_white-on-gray_400sq.png

{{ grav.page.media['leflar_white-on-gray_400sq.png'].url|raw }} // returns nothing 

{{ grav.page.media["2014-OAC-White-Logo_400sq.png"].resize(400, 200).html()|raw }} // returns nothing

<img src="{{ url(thisimg)|e }}" alt="{{ tabimage.title|e }}" /> // renders leflar_white-on-gray_400sq.png
```

Screenshot of what gets rendered. The image name and the image work, but grav.page.media() returns nothing:

![Screen Shot 2021-05-13 at 8 41 39 AM](https://user-images.githubusercontent.com/998832/118127052-28d76280-b3c7-11eb-9149-dc8c129e6c24.png)

Here's the header YAML for this page:

```
title: Partners
media_order: 'leflar_white-on-gray_400sq.png,2014-OAC-White-Logo_400sq.png,oft-white-on-gray_400sq.png,cfc-white-on-grey_400sq.png'
tabimages:
    -
        title: 'The Leflar Foundation'
        text: null
        image: leflar_white-on-gray_400sq.png
        link: 'https://www.leflarfoundation.com/'
        label: 'Visit the Leflar Web site'
    -
        title: 'Ontario Arts Council'
        text: null
        image: 2014-OAC-White-Logo_400sq.png
        link: 'https://www.arts.on.ca/home?lang=en-ca'
        label: 'Visit the OAC Web site'
```
