### ISSUE TITLE
Joomla Hydrogen 'textarea' style improper

### ISSUE THREAD

**Issue by bomkallo** [gantry/gantry5#1973]
File location: \g5_hydrogen\scss\hydrogen-joomla\_forms.scss
Line: 19 -> textarea, Line 39 -> height: 19px

In one of previous releases textarea has been affected by that 19px. The default behavior of that field is then improper and should be separated and changed to auto elsewhere.

**Comment by bomkallo** [comment]
From N8Solutions: Helium theme goes same issue, but there is 41px instead of 19px.

**Comment by N8Solutions** [comment]
The following bit of code was found on lines 25 through 52 of the `_forms.scss` file located at `/templates/g5_helium/scss`.
```scss
textarea,
input[type="text"], input[type="password"], input[type="datetime"], input[type="datetime-local"], input[type="date"], input[type="month"], input[type="time"], input[type="week"], input[type="number"], input[type="email"], input[type="url"], input[type="search"], input[type="tel"], input[type="color"], .uneditable-input {
    color: $base-text-color;
    background-color: $base-background;
    border: 1px solid $base-border-color;
    box-sizing: border-box !important;
    @include transition(border 0.2s linear, box-shadow 0.2s linear:);
    height: 41px;

    .input-prepend &, .input-append & {
        padding: 0.35rem;
        max-width: 95%;
    }
}
```
I overrode it in the `custom.scss` with the following line of code:
```scss
textarea {height: auto !important;}
```
and the textarea of the contact form displays properly now.
