### ISSUE TITLE
Nested collection.list issues

### ISSUE THREAD

**Issue by kat05** [gantry/gantry5#2089]
As mentioned in Slack, there are still issues with nested collections in Gantry 5.4.16

To see the issue, just install a Notio RocketLauncher, open the Home outline and open for example either the Article Tabs particle (Header) or the News Tabs particle (SideBar)

Then hit the little icon that says 'Edit all' and you wont see the nested items at all.
You only do see them when editing the items individually, please see 2 attached screenshots. 

![notio_-_administration 1](https://user-images.githubusercontent.com/5719486/29563159-b29d8ce4-873c-11e7-993f-5ceec1937201.jpg)
![notio_-_administration](https://user-images.githubusercontent.com/5719486/29563160-b2a43256-873c-11e7-8de5-5e56bfebf2d7.jpg)

**Comment by mahagr** [comment]
@jakub This is a bug in the particle, items field is missing a dot.

```yaml
        _tabs:
          type: container.tabs
          fields:
            _tab_collection:
              label: Particle Items
              overridable: false
              fields:
                items: <---
```
