### ISSUE TITLE
Header modifications questions

### ISSUE THREAD

**Issue by Quincyto** [gantry/gantry5#2098]
Hello!

I'm trying and investigating the gantry things with some templates, and i tried to create a header containet in order to modify the grid that logo "section takes" but i had no success doing it i've created a new layout: 

```yaml
layout:
  /container-header/:
     -
      - logo 30:
         - position-sidebar
      - main 70:
          - position-header

structure:
  sidebar:
    subtype: aside
    block:
      fixed: 1
  logo:
    subtype: aside
    block:
      fixed: 1
```

It worked but header css was not applied... then i tried with anothe composition:

```yaml
layout:
  /container-header/:
    -
      - header 30:
          - position-logo
      - header 70:
         - position-header
structure:
  sidebar:
    subtype: aside
    block:
      fixed: 1
  logo:
    subtype: aside
    block:
      fixed: 2
```

It worked better but css not yet.

Then the question is how i can configure a block in a grid to take 2 places but in vertical?

Thanks you in advance, i'm looking for this information but i didn't found anything in documentations, etc...
