### ISSUE TITLE
[Particle] Field Types - Radios

### ISSUE THREAD

**Issue by thexmanxyz** [gantry/gantry5#2164]
Hey there,

I noticed a Bug with the field type `input.radios`. I would have rather prepared a pull request however IDK where the affected code is located. But to the bug description and lets assume the following field definition:

```
 my.radio.button:
   type: input.radios
   label: My Radio
   description: A test of radio buttons.
   default: abutton
   options:
      abutton: A Button
      bbutton: B Button
```

A normal definition which worked for all of my other field types (as far as I have seen). However, as soon as I choose an identifier like `my.radio.button` for my radio input the field would always be reset to default, after saving the particle which contains this field. Moreover it's deactivated each time I save it (the right checkbox will be set to unchecked). I traced the problem down to the `.` in the field identifier. As soon as for `input.radios` an idenfier with an point in the string is chosen the `input.radios` does not act as it should. It simply doesn't hold the modified state. I also tried a more uncommon identifier like the one i described in the example to be sure that there are no other interferences from inheritance or whatever.

Simply try it and you will be able to reproduce it easily.
