### ISSUE TITLE
[Particle] Field Types - Collection.List

### ISSUE THREAD

**Issue by thexmanxyz** [gantry/gantry5#2165]
Hello,

I've to open another issue because I noticed another thing that's somehow related to #2164. However it's possible that the error that I'm receiving happend because the YAML I created is not allowed by design. Even though let me state the issue I noticed. If it's irrelevant or not allowed simply close it. 

But I want to share it because it throws a stacktrace. It's basically the same thing like in #2164 but an stacktrace is thrown. If I use a `.` within the identifier of a `collection.list` I receive a stacktrace in the backend as soon as i want to edit an added item. In this case as soon as I click on a new item to access the "anything" field of the collection item (from the example below).

```
some.test.collection:
  type: collection.list
  array: true
  label: Testcollection
  description: A collection that throws a stacktrace.
  value: title
  ajax: true
  fields:
    .title:
      type: input.text
      description: A simple title
      label: Title
    .anything:
      type: input.text
      description: Anything just demonstration
      placeholder: Some placeholder
      label: Path
```
Edit: I noticed that the issue not always occurs when a `.` is in the identifier. There must be something else involved because sometimes it works without any flaws. However it has something todo with hierarchy and when other elements are bound to the same namespace. e.g. if something else is defined to the same namespace path e.g. `some.test.x.y.z` for the above example. I will try to reproduce it and report back.

Edit2: In my problematic YAML there is no problem with wrong namespacing and there are also no duplicates. It must have something todo with order the fields are attached to the namespace. If I remove the particle from the particle folder, change the field order of the problematic fields and reattach it with modified order it magically works.

I also attach the anonymized stack trace I'm receiving. I use J3 and the latest version of G5.

![stacktrace_a](https://user-images.githubusercontent.com/17965908/32399831-c9b6c840-c0f9-11e7-9404-c813f0ef722f.png)
![stacktrace_b](https://user-images.githubusercontent.com/17965908/32399832-c9d50e86-c0f9-11e7-83ec-f35458438e81.png)
