### ISSUE TITLE
Enhancement: columns option for particle

### ISSUE THREAD

**Issue by linkinformatica** [gantry/gantry5#2172]
I'd like to suggest an enhancemnt for particle, with collection.list. 

yaml file, particle section
```
columns:
      type: select.selectize
      label: columns
      description: number of columns.
      placeholder: ' - '
      default: size-100
      options:
          size-100: full
          size-50: 2 columns
          size-33: 3 columns
          size-25: 4 columns
          size-20: 5 columns
```

and in the twig file
```
<div class="g-grid samples">
            {% for sample in particle.samples %}
                <div class="g-block {{ sample.visibility }} {{ particle.columns }}">
                       // code here
                 </div> {# end g-block #}
            {% endfor %}
</div>
```
