### ISSUE TITLE
Date particle in other languages

### ISSUE THREAD

**Issue by Omegatcu** [gantry/gantry5#221]
I asked this in the Chat - has anyone an idea how we could modify the Particle to set the LC_LOCAL and influence how the Date is shown?

Right now it is in english all the time which might be nice but doesn't help for a bunch of sites.

**Comment by sural98** [comment]
RT dev might offer one so that it can work for all languages.
Joomla had injected this in language (*.ini) file as known.

**Comment by w00fz** [comment]
Hmmm, I know how you can [change the timezone](http://twig.sensiolabs.org/doc/filters/date.html#timezone) from a twig but I don't think we have the ability to format it based on `LC_LOCAL` yet.

@mahagr perhaps we should look into this? http://twig.sensiolabs.org/doc/extensions/intl.html

**Comment by mahagr** [comment]
Its something that was added to Grav a while ago. Might do something similar on this.

**Comment by marktaylor46** [comment]
Just adding another member in RT forum asked same question...
http://www.rockettheme.com/forum/gantry-framework/244471-translate-date-on-gantry-5?start=0#1216484

**Comment by marktaylor46** [comment]
Another member with same issue [url]http://www.rockettheme.com/forum/joomla-template-salient/247028-how-to-change-the-name-for-date-and-month-in-the-date-particle?start=0#1230692[/url]

**Comment by marktaylor46** [comment]
Another member with same issue http://www.rockettheme.com/forum/joomla-template-kraken/250475-particle-date-in-english-in-french-language-site?start=0#1249003

**Comment by DanGthatRokGallery** [comment]
and another member with this issue -> http://www.rockettheme.com/forum/joomla-template-ambrosia/250154-translate-days-and-months

**Comment by mahagr** [comment]
I'm moving this issue to the next release, mostly to give it higher priority.

**Comment by Omegatcu** [comment]
Just a question - is the date always returned in english or is it dependend on the system Language?
If it is always in english i might be able to do a workaround for the Particle.

**Comment by mahagr** [comment]
The format is controlled by date function in PHP, but in Joomla it might be better to override it to use JDate instead.

**Comment by marktaylor46** [comment]
Another member with same issue http://www.rockettheme.com/forum/joomla-template-salient/257035-date-language

**Comment by DanGthatRokGallery** [comment]
Another request for Date Language -> http://www.rockettheme.com/forum/joomla-template-requiem/257378-how-to-change-gantry-date-particle-default-language

**Comment by marktaylor46** [comment]
Another member reports the same http://www.rockettheme.com/forum/joomla-template-interstellar/258093-can-not-find-the-feedback-form?start=0#1288567

**Comment by marktaylor46** [comment]
Another member with same issue http://www.rockettheme.com/forum/joomla-template-ambrosia/259163-date-particle-in-other-languages?start=0#1294254

**Comment by Vanguger** [comment]
Example: date Joomla System - 

file: templates/G5_TEMPLATE/custom/particles/date.yaml - 

```
name: Date
description: Display a date.
type: particle
icon: fa-calendar

form:
  fields:
    enabled:
      type: input.checkbox
      label: Enabled
      description: Globally enable date particles.
      default: true

    css.class:
      type: input.selectize
      label: CSS Classes
      description: CSS class name for the particle.
      default: date

    date.formats:
      type: select.date
      label: Format
      description: Select preferred date format.
      default: j F Y
      placeholder: 'Select...'
      selectize:
          allowEmptyOption: true
      options:
          'F Y': Date1
          'j F Y': Date2
```

file: templates/G5_TEMPLATE/custom/particles/date.html.twig - 

```
{% extends '@nucleus/partials/particle.html.twig' %}

{% block particle %}

	{% set ln = ['','JANUARY','FEBRUARY','MARCH','APRIL','MAY','JUNE','JULY','AUGUST','SEPTEMBER','OCTOBER','NOVEMBER','DECEMBER'] %}

	{% set d = "now"|date("j") %}
	{% set m = "now"|date("n") %}
	{% set y = "now"|date("Y") %}
	{% set s = ln[m]|trans %}
	{% set f = particle.date.formats %}

	{% if f == 'F Y' %}{% set dt = s~" "~y %}{% endif %}
	{% if f == 'j F Y' %}{% set dt = d~" "~s~" "~y %}{% endif %}

    <div class="g-date">
        <span> {{ dt }}  </span>
    </div>

{% endblock %}
```
