### ISSUE TITLE
Hydrogen don't show active preset if color is orange

### ISSUE THREAD

**Issue by MarcosRakesh** [gantry/gantry5#2233]
Hydrogen theme don't show active preset on this preset (don't like orange color), when refreshing the page is shows the star only for few seconds and vanish. On helium is showing.
```
preset5:
  image: 'gantry-assets://images/presets/preset5.png'
  description: 'Orange'
  colors:
    - '#f57c00'
    - '#ff9800'
    - '#ffb24d'

  styles:
    base:
      background: '#ffffff'
      text-color: '#000000'
    accent:
      color-1: '#ff9800'
      color-2: '#f57c00'
    header:
      background: '#f57c00'
      text-color: '#000000'
    navigation:
      background: '#ff9800'
      text-color: '#000000'
      overlay: 'rgba(0,0,0,0.6)'
    showcase:
      background: '#ffb24d'
      text-color: '#000000'
    feature:
      background: '#fafafa'
      text-color: '#000000'
    subfeature:
      background: '#fafafa'
      text-color: '#000000'
    main:
      background: '#fafafa'
      text-color: '#000000'
    footer:
      background: '#212121'
      text-color: '#ffffff'
    offcanvas:
      background: '#212121'
      text-color: '#ffffff'
```
