### ISSUE TITLE
Grav Localisation for Blog item navigation does not work.

### ISSUE THREAD

**Issue by DominiqueVial** [gantry/gantry5#2373]
I added the following code on `languages/fr.yaml`:
```
PLUGIN_GANTRY5:
    GANTRY5_ENGINE_BLOG_ITEM_NEXT_POST: "Suivant"
    GANTRY5_ENGINE_BLOG_ITEM_PREV_POST: "Précédent"
    GANTRY5_ENGINE_READMORE: "Plus..."
```

This doesn't work.

Now I duplicate `user/plugins/gantry5/admin/translations/en` and named the cloned directory `fr`. I then translate the content on `fr/nucleus.yaml`. It works!

It works but it's a very bad practice as these translations will be lost on plugin update.

Do I miss something?
