### ISSUE TITLE
Custom particle layout gets generated as static template.

### ISSUE THREAD

**Issue by Ayanami251379** [gantry/gantry5#2388]
I have been using a custom "social" particle to grab the current URL of the page into social links.

I used the layout editor to add the particle to the pages, but this limits my control on what pages it gets displayed on.

When I used Joomla's Module feature and added a new Gantry module with my custom code it always seems to create a template for the Gantry module. The first time I load a page with the new module the template is created and subsequent loads does not execute the twig code in the Gantry module anymore.

I am not sure if this is due to my code not being in correct format for this method or due to some other factors.

File: social_custom.yaml
```
name: Social Custom
description: Display social buttons.
type: particle
icon: fa-share-alt

configuration:
  caching:
    type: static

form:
  fields:
    enabled:
      type: input.checkbox
      label: Enabled
      description: Globally enable social particles.
      default: true

    css.class:
      type: input.selectize
      label: CSS Classes
      description: CSS class name for the particle.
      default: social

    title:
      type: input.text
      label: Title
      description: Customize the title text.
      placeholder: Enter title

    display:
      type: input.radios
      label: Display
      description: How to display the Social Icons
      default: both
      options:
        icons_only: Icons Only
        text_only: Text Only
        both: Both

    items:
      type: collection.list
      array: true
      label: Social Items
      description: Create each social item to display.
      value: name
      ajax: true

      fields:

        .name:
          type: input.text
          label: Name
          skip: true

        .icon:
          type: input.icon
          label: Icon

        .text:
          type: input.text
          label: Text

        .link:
          type: input.text
          label: Link
          
        .islink:
          type: input.checkbox
          label: Is Link
          description: Use the link provided above
          default: true
          
        .isemail:
          type: input.checkbox
          label: Is Email
          description: Convert the current page URL to a Facebook share link
          default: false
          
        .emailaddress:
          type: input.text
          label: Email Address
          description: The default email address to send the links to.
          default: ""
        
        .isfacebook:
          type: input.checkbox
          label: Is Facebook
          description: Convert the current page URL to a Facebook share link
          default: false
          
        .istwitter:
          type: input.checkbox
          label: Is Twitter
          description: Convert the current page URL to a Twitter share link
          default: false
          
        .iswhatsapp:
          type: input.checkbox
          label: Is Whatsapp
          description: Convert the current page URL to a Whatsapp share link
          default: false
          
        .target:
          type: select.select
          label: Target
          description: Target browser window when item is clicked.
          placeholder: 'Select...'
          default: _blank
          options:
              _parent: Self
              _blank: New Window

```

File: social_custom.html.twig
```
{% extends '@nucleus/partials/particle.html.twig' %}

{% block particle %}
    {% if particle.title %}<h2 class="g-title" style="text-align: left;">{{ particle.title|raw }}</h2>{% endif %}
    <div class="g-social {{ particle.css.class }}">
        {% for item in particle.items %}
			{% set current_url = joomla.call('JUri::current')|url_encode %}
			{% set current_url_encoded = joomla.call('JUri::current') %}
			
			{% if item.islink %}
				{% set current_url_encoded = item.link|e %}
			{% endif %}
			
			{% if item.isemail %}
				{% set current_url_encoded = 'mailto:?&subject=I am sharing this page with you&body=' %}
				{% set current_url_encoded = current_url_encoded ~ current_url %}
			{% endif %}
			
			{% if item.isfacebook %}
				{% set current_url_encoded = 'https://www.facebook.com/sharer/sharer.php?u=' %}
				{% set current_url_encoded = current_url_encoded ~ current_url %}
			{% endif %}
			
			{% if item.istwitter %}
				{% set current_url_encoded = 'https://twitter.com/home?status=I%20am%20sharing%20this%20page%3A%0A' %}
				{% set current_url_encoded = current_url_encoded ~ current_url %}
			{% endif %}
			
			{% if item.iswhatsapp %}
				{% set current_url_encoded = 'whatsapp://send?text=I am sharing this page: ' %}
				{% set current_url_encoded = current_url_encoded ~ joomla.call('JUri::current') %}
				{% set current_url_encoded = current_url_encoded ~ '\" data-action=\"share/whatsapp/share\"' %}
			{% endif %}
			
            <a target="{{ item.target|default('_blank')|e }}" href="{{ current_url_encoded }}" title="{{ item.text|e }}" aria-label="{{ item.text|e }}">
                {% if particle.display in ['both', 'icons_only'] %}<span class="{{ item.icon|e }}"></span>{% endif %}
                {% if particle.display in ['both', 'text_only'] %}<span class="g-social-text">{{ item.text|e }}</span>{% endif %}
            </a>
        {% endfor %}
    </div>
{% endblock %}

```
