### ISSUE TITLE
Translation for Particle's "Label/Description" (Grav v1.5.3/Gantry v5.4.26)

### ISSUE THREAD

**Issue by federone** [gantry/gantry5#2403]
Hi.
as i see it is possible to use translations for `separator.note` fields, for example:

```
_info:
  type: separator.note
  class: alert alert-info
  content: GANTRY5_PARTICLE_MENU_INFO
```
but is it possible to use for other fields, for example:
```
my_field:
  type: input.text
  label: GANTRY5_PARTICLE_MY_FIELD_LABEL
  description: GANTRY5_PARTICLE_MY_FIELD_DESCR
```
it is not possible, right? or am i missing something?

Best Regards,
