### ISSUE TITLE
Wordpress 404 error - Not loading the error outline

### ISSUE THREAD

**Issue by joomlabeat** [gantry/gantry5#2449]
On Wordpress when I hit a 404 page, gantry won't load the error outline (_error layout). Default outline is still loading.
So, I am trying to add custom particles and styling on my 404 outline but I can't show them in the 404 front output.
What may be causing this?

**Comment by newkind** [comment]
Check your 404.php file if it's set up correctly. You can compare it to the Helium 404.php file to be sure.

**Comment by joomlabeat** [comment]
I guess you mean if it's setting the layout to the error one inside the 404 php. My bad that I didn't mention it and although I m out now, I remember the 404 template file is the original gantry one and that is using the setlayout method to set the _error outline before rendering.

**Comment by joomlabeat** [comment]
So - I have the 404.php which gets loaded on a 404 error. It's the core gantry 404.php, it contains:

```
$gantry = Gantry\Framework\Gantry::instance();
$theme  = $gantry['theme'];

$theme->setLayout('_error', true);

```

**Comment by joomlabeat** [comment]
@newkind :: I am not sure I understand what you ask with this question. Do you mean what is the name of the layout, or something else?

**Comment by newkind** [comment]
Can you paste the whole YAML of your `layouts/error.yaml` ?

**Comment by joomlabeat** [comment]
Sure @newkind , here you are:

**/layouts/_error.yaml**
```
version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1457453164
layout:
  /navigation/:
    -
      - 'logo-9608 15'
      - 'menu-6409 65'
      - 'social-3171 20'
  /header/:
    -
      - custom-8642
  /intro/: {  }
  /features/: {  }
  /utility/: {  }
  /above/: {  }
  /testimonials/: {  }
  /expanded/: {  }
  /container-main/:
    -
      -
        'mainbar 75':
          -
            - system-content-1587
      -
        'sidebar 25': {  }
  /footer/:
    -
      - 'logo-9571 10'
      - 'copyright-1736 30'
      - 'horizontalmenu-9034 45'
      - 'totop-8670 15'
  /offcanvas/:
    -
      - mobile-menu-5697
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
  header:
    type: section
    subtype: header
    attributes:
      boxed: ''
      class: ''
  intro:
    type: section
    attributes:
      boxed: ''
  features:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  above:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  mainbar:
    type: section
    subtype: main
    attributes:
      class: ''
    block:
      variations: center
  sidebar:
    type: section
    subtype: aside
  container-main:
    attributes:
      boxed: ''
  footer:
    type: section
    subtype: footer
    attributes:
      boxed: ''
  offcanvas:
    attributes:
      boxed: ''
content:
  logo-9608:
    title: 'Logo / Image'
  social-3171:
    block:
      class: g-social-header
  custom-8642:
    title: 'Custom HTML'
    attributes:
      html: "<h2 class=\"g-title\">We are sorry!</h2>\n<p>Gantry 5 provides a custom error page for you to configure with either positions, particles or a combination of both, as well as styling.</p>"
  logo-9571:
    title: 'Logo / Image'
    attributes:
      image: 'gantry-media://logo/logo-footer.svg'
  horizontalmenu-9034:
    title: 'Horizontal Menu'
    attributes:
      items:
        -
          text: Gantry
          link: 'http://gantry.org'
          name: Gantry
        -
          text: Documentation
          link: 'http://docs.gantry.org'
          name: Documentation
        -
          text: Download
          link: 'http://gantry.org/downloads'
          name: Download
  totop-8670:
    title: 'To Top'
```

### Adding also the .yaml contents from the custom/config/_error 

**/custom/config/_error/index.yaml**
```
name: _error
timestamp: 1547538142
version: 7
preset:
  image: 'gantry-admin://images/layouts/2-col-right.png'
  name: default
  timestamp: 1539840824
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  info: Info
  copyright: Copyright
  header: Header
  mainbar: Mainbar
  footer: Footer
  offcanvas: Untitled
particles:
  messages:
    system-messages-4358: 'System Messages'
  logo:
    logo-9062: 'Logo / Image'
    logo-7340: 'Logo / Image'
  menu:
    menu-6594: Menu
    menu-3486: Menu
  custom:
    custom-8750: 'Custom HTML'
    custom-3822: 'Custom HTML'
  content:
    system-content-1587: 'Page Content'
  contactus:
    contactus-1796: Contactus
  spacer:
    spacer-3191: Spacer
    spacer-7837: Spacer
  klnewsletter:
    klnewsletter-1170: 'KL Newsletter'
  social:
    social-2769: Social
  copyright:
    copyright-6079: Copyright
  mobile-menu:
    mobile-menu-5926: Mobile-menu
inherit:
  default:
    navigation: navigation
    system-messages-4358: system-messages-7972
    logo-9062: logo-9608
    menu-6594: menu-6409
    custom-8750: custom-6669
    custom-3822: custom-5864
    footer: footer
    logo-7340: logo-9571
    contactus-1796: contactus-5905
    spacer-3191: spacer-3904
    klnewsletter-1170: klnewsletter-1412
    spacer-7837: spacer-9083
    social-2769: social-5899
    copyright: copyright
    menu-3486: menu-3614
    copyright-6079: copyright-1736
    offcanvas: offcanvas
    mobile-menu-5926: mobile-menu-5697
```

**/custom/config/_error/layout.yaml**
```
version: 2
preset:
  image: 'gantry-admin://images/layouts/2-col-right.png'
  name: default
  timestamp: 1539840824
layout:
  navigation: {  }
  /header/: {  }
  /intro/: {  }
  /container-main/:
    -
      -
        mainbar:
          -
            - system-content-1587
  /info/: {  }
  footer: {  }
  copyright: {  }
  offcanvas: {  }
structure:
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  header:
    attributes:
      boxed: ''
      class: ''
  intro:
    type: section
    attributes:
      boxed: ''
  mainbar:
    type: section
    subtype: main
  container-main:
    attributes:
      boxed: ''
  info:
    type: section
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  copyright:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children

```
