### ISSUE TITLE
input.colorpicker in Particle does not generate SCSS variable

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#247]
Is this supposed to work? 
Here's what I have:

http://i.imgur.com/XpZbFOM.png

```
name: Offcanvas Toggle Button
description: Displays the Offcanvas Toggle Button so the user can place it wherever they want.
type: particle

form:
  fields:
    enabled:
      type: input.checkbox
      label: Enabled
      description: Globally enable to the particles.
      default: true

    icon:
      type: input.icon
      label: Icon
      description: Select an icon for the Toggle button.
      default: fa fa-bars fa-fw

    text:
      type: textarea.textarea
      label: Text
      description: Type in the Text for the Toggle button.

    color-main:
      type: input.colorpicker
      label: Color
      default: "#439A86"
    
    color-hover:
      type: input.colorpicker
      label: Color on hover
      default: "#8F4DAE"
```

I expect the SCSS variables to be `$offcanvastoggle-color-main` and `$offcanvastoggle-color-hover` but the following code does not work. It does not take the color a choose in the Color Picker. I "Recompile the CSS" for the correct Configuration, clear the Joomla Cache and it still does not work:

```
.offcanvas-toggle { 
	color: $offcanvastoggle-color-main;
	display: block;
	position: absolute;
	z-index: 10;
	cursor: pointer; 
	&:hover {
		color: $offcanvastoggle-color-hover;
	}
}
```

I also added an `input.colorpicker` field to the default "Sample Content" particle and it also does not work.

So I'm wondering if I'm using wrong variable names or if it is a bug?
