### ISSUE TITLE
gantry menu editor not synch wordpress menu

### ISSUE THREAD

**Issue by manuel-84** [gantry/gantry5#2473]
if you edit in WP submenus items, for a menu already saved in Gantry, when you go back to gantry menu editor you will not see the new menu voices... and there are other problems like it's not going to save changes

this is `/custom/config/menu/navigation.yaml`

```yaml
ordering:
  chi-siamo:
    -
      chi-siamo: ''
    -
      il-consorzio: ''
      la-storia: ''
    -
      la-sede: ''
      privacy-policy: ''
  corsi:
    -
      corsi: ''
      tica/economia-e-gestione-dei-servizi-turistici: ''
      tica/biotecnologie-industriali-e-ambientali: ''
      tica/tecnologie-alimentari: ''
      tica/viticoltura-ed-enologia: ''
      tica/Qualità-e-Sicurezza-dei-Prodotti-Alimentari: ''
      tica/scuola-di-specializzazione-in-beni-archeologici: ''
    - {  }
  futuri-studenti: ''
  consorzio-uno: ''
  orientamento:
    -
      orientamento: ''
    -
      'Studiare-all''università': ''
      agevolazioni-per-il-diritto-allo-studio: ''
    -
      unorienta: ''
  noi-siamo-uno: ''
  notizie:
    -
      notizie: ''
    -
      biotin: ''
      egst: ''
    -
      tvea---ve: ''
      tvea---ta: ''
items:
  chi-siamo:
    object_id: 29
    dropdown: fullwidth
    dropdown_dir: center
    dropdown_hide: '0'
    width: auto
    columns:
      - 33.3
      - 33.3
      - 33.3
  chi-siamo/chi-siamo:
    object_id: 1226
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
  chi-siamo/il-consorzio:
    object_id: 288
  chi-siamo/la-storia:
    object_id: 292
  chi-siamo/la-sede:
    object_id: 294
  chi-siamo/privacy-policy:
    object_id: 9
  corsi:
    object_id: 1142
    columns:
      - 50
      - 50
  corsi/corsi:
    object_id: 1227
  futuri-studenti:
    object_id: 31
  consorzio-uno:
    object_id: 32
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
    image: 'gantry-media://logo-menu.svg'
    icon_only: '1'
  orientamento:
    object_id: 33
    columns:
      - 33.3
      - 33.3
      - 33.3
  orientamento/orientamento:
    object_id: 1225
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
  'orientamento/Studiare-all''università':
    object_id: 516
  orientamento/agevolazioni-per-il-diritto-allo-studio:
    object_id: 517
  orientamento/unorienta:
    object_id: 518
  noi-siamo-uno:
    object_id: 34
  notizie:
    object_id: 1607
    columns:
      - 33.3
      - 33.3
      - 33.3
  notizie/notizie:
    object_id: 1614
  notizie/biotin:
    object_id: 5
  notizie/egst:
    object_id: 4
  notizie/tvea---ve:
    object_id: 11
  notizie/tvea---ta:
    object_id: 10
  didattica/economia-e-gestione-dei-servizi-turistici:
    object_id: 384
  didattica/biotecnologie-industriali-e-ambientali:
    object_id: 387
  didattica/tecnologie-alimentari:
    object_id: 389
  didattica/viticoltura-ed-enologia:
    object_id: 392
  didattica/Qualità-e-Sicurezza-dei-Prodotti-Alimentari:
    object_id: 395
  didattica/scuola-di-specializzazione-in-beni-archeologici:
    object_id: 397
  didattiqa/__particle-2nd1v:
    type: particle
    particle: custom
    title: Didattica
    options:
      particle:
        enabled: '1'
        html: '<b>Didattica</b>'
        twig: '0'
        filter: '0'
      block:
        extra: {  }
  servizi/__particle-0cEVp:
    type: particle
    particle: custom
    title: Orientamento
    options:
      particle:
        enabled: '1'
        html: '<b>{{ __(''Orientamento'', ''g5_uno'') }}</b>'
        twig: '1'
        filter: '0'
      block:
        extra: {  }
```

i have to delete this file to be able to reconstruct a new menu correctly
