### ISSUE TITLE
Gantry5 Access in Grav with admin.themes Permission

### ISSUE THREAD

**Issue by thekenshow** [gantry/gantry5#2488]
The `user/plugins/gantry5/pages/gantry.md` has this frontmatter:

```
---
title: Gantry Templates

cache_enable: false
process:
    markdown: false
    twig: false
    
access:
    admin.themes: true
    admin.super: true
---
```

But for users with only `admin.themes` permission, the Gantry5 menu doesn't appear because gantry.php authorizes like so:

```
    public function onAdminMenu()
    {
        $nonce = Utils::getNonce('gantry-admin');
        $this->grav['twig']->plugins_hooked_nav['Gantry 5'] = [
            'authorize' => 'admin.gantry',
            'location' => 'gantry',
            'route' => "gantry/configurations/default/styles?nonce={$nonce}",
            'icon' => 'fa-gantry'
        ];
    }
```
The user requires both `admin.themes` and `admin.gantry`. Is that the intended behaviour?
