### ISSUE TITLE
Background video on Page Surround

### ISSUE THREAD

**Issue by chatman1974** [gantry/gantry5#2751]
Hi all.

### How to set parameters in ```page.html.twig``` file for calls from yaml file? I want to inject some custom html codes with parameters that coming from custom **yaml** file.?   And if i created custom.yaml file in folder "/custom/blueprints/pagesurround.yaml" that including needed paramaters, how i set the call paramters in **page.html.twig** file?

This is the pagesurround.yaml file that including the video.picker input field:
```
name: Page Surround Styles
description: Page Surround section styles
type: core

form:
  fields:    
    video-file-here:
      type: input.videopicker
      label: Video
      description: "Select background video."
      default: ""
```
Inserting html code for video background between ```<div id="g-page-surround"></div>``` tag in page.html.twig file is working:

```
<!DOCTYPE {{ gantry.config.page.doctype|default('html')|raw }}>
<html{{ gantry.page.htmlAttributes|raw }}>
    {{ page_head|raw }}
    {% block page_body -%}
    <body{{ gantry.page.bodyAttributes({'class': [offcanvas_position, gantry.page.preset, 'g-style-' ~ gantry.theme.preset]})|raw }}>
        {{ gantry.config.page.body.body_top|raw }}
        {{ body_top|raw }}
        {{ page_offcanvas|raw }}
        <div id="g-page-surround">

<div id="BgVideo" style="position: relative; overflow: hidden;"><video src="{{ url(www.exampledomain.org/video.mp4)|e }}" autoplay loop playsinline muted style="position: absolute; z-index: -1;"></video>
        {{ html|raw }}
</div>

            {% if page_offcanvas|trim -%}
            <div class="g-offcanvas-hide g-offcanvas-toggle" role="navigation" data-offcanvas-toggle aria-controls="g-offcanvas" aria-expanded="false"><i class="fa fa-fw fa-bars"></i></div>
            {%- endif %}
            {{ page_top|raw }}
            {{ page_layout|raw }}
            {{ page_bottom|raw }}
        </div>
        {{ body_bottom|raw }}
        {{ page_footer|raw }}
        {{ gantry.config.page.body.body_bottom|raw }}
    </body>
    {%- endblock %}

</html>
{% endblock -%}

```
So what i should write instead ```www.exampledomain.org/video.mp4``` in page.html.twig file that calls video file from video-file-here input field for video html code.

```video-file-here = input field name from pagesurround.yaml file.```

The second thing is...

What if i want to add rules for video file that coming from user input field, provided by yaml file ? 
Something like that : 
 - If file selected from input field: Add video to background.
 - If no file selected from input field: Nothing to do.

I need to add code to page.html.twig file in ```<div id="g-page-surround"></div>``` tag somethings like that :

```
{% if video-file-here %}
    <div id="BgVideo" style="position: relative; overflow: hidden;"><video src="{{ url(video-file-here)|e }}" autoplay loop playsinline muted style="position: absolute; z-index: -1;"></video>{% endif %}
        {{ html|raw }}
    {% if video-file-here %}</div>{% endif %}
```
```video-file-here = input field name from pagesurround.yaml file.```
Please help me...
Sory for my stupid English :(

![bgvid](https://user-images.githubusercontent.com/69113726/108061019-c2ad9e80-7068-11eb-9f35-1f12215b2e21.jpg)

**Comment by dmleeman** [comment]
Until a better answer arrives - have you tried using a Video background Atom to see where the generated code sits in the structure?

**Comment by chatman1974** [comment]
> Until a better answer arrives - have you tried using a Video background Atom to see where the generated code sits in the structure?

I looked for an Atom code like that, but it's written code for a video on youtube. I need code to add videos from my server. Videos from user input field.

**Comment by dmleeman** [comment]
Joomlead does have a particle that allows you to pick a file from Youtube, Vimeo or Local folder. The TWIG and YAML from that might be of use to you?
The default is to open in a modal, but, it might be of guidance. You seem capable of changing this to background
Here is the link to the demo of the Particle
http://demo.joomlead.com/particles/index.php/particles/video

**Comment by chatman1974** [comment]
I solved the problem by adding the lines I need for the video to an existing body.yaml file that creates the "Body Attributes" tab in Page Settings, and adding the necessary code to the page.html.twig file.

Working way is :

Added extra lines for video in body.yaml
```
video:
      type: input.videopicker
      label: Video Background
      description: "Select background video."
      default: ""
    opacity:
      type: input.text
      label: Video Opacity
      description: Define the opacity of the video (0 to 1).
      placeholder: "Default 1"
      pattern: '\d+(\.\d+){0,1}'
      default: ""
```
Then added extra lines in page.html.twig too
```
{% set attr_video = gantry.config.page.body.video %}
{% if gantry.config.page.body.opacity %}
{% set attr_opacity = gantry.config.page.body.opacity %}
{% else %}
{% set attr_opacity = 1 %}
{% endif %}
```
```
{% if attr_video %}
<div id="BgVideo" style="position: relative; opacity: {{attr_opacity}};">
<video src="{{ url(attr_video)|e }}" autoplay loop playsinline muted style="position: fixed; z-index: -2;"></video></div>
{% endif %}
{{ html|raw }}
{% if attr_video %
}{% endif %}
```
