### ISSUE TITLE
Asking help about Input Types when adding Custom Fields in yaml files

### ISSUE THREAD

**Issue by chatman1974** [gantry/gantry5#2757]
Hi.
I enabled overlay opacity option input field in custom/blueprints/header.yaml file by adding lines that :
```
overlay-opacity:
      type: input.text
      label: Overlay Opacity
      description: 'Provide the opacity of the linear gradient overlay.'  
```
Then added line to ```custom/scss/configuration/_colors.scss``` like that :
```
// Header
$header-overlay-opacity: 0.5 !default;
```
Then i customized the ```custom/scss/helium/sections/_header.scss``` file by adding code like that:
```
opacity: $header-overlay-opacity;
```
If i don't input any value from ```joomla/admin panel/themes/helium/styles/Header Section Styles/ Overlay Opacity Input Field```, its adding 0.5 opacity for overlay as default from ```custom/scss/configuration/_colors.scss ```
The result in chrome developer console is : ``` opacity: 0.5;```
It's work fine.
But if i provide some value from ```joomla/admin panel/themes/helium/styles/Header Section Styles/ Overlay Opacity Input Field``` somethings like ```Overlay Opacity : 0.3```, then its changing the code like that: ~~opacity: '0.3';~~

I mean it's adding ```' '``` marks in opacity value. By the cause, it's not working. How i can disable to ```' ' ```marks from opacity field?

I tried all of input types:
```
input.text
input.number
input.selectize
```
But still don't works.
