### ISSUE TITLE
G5.5.5 - editing layout gives "incorrect DATE/TIME value"

### ISSUE THREAD

**Issue by marktaylor46** [gantry/gantry5#2948]
Just editing anything on layout gives the above error - I have login details if you need them

![2021-11-24_17-52-04](https://user-images.githubusercontent.com/11683218/143290696-a92894bb-5fd5-482a-8a7c-738cb74dc30e.png)

**Comment by hypermodernorg** [comment]
Having the same issue with the joomla article particle, and the news slider particle

**Comment by mahagr** [comment]
Unfortunately, I cannot reproduce this locally. 

@hypermodernorg Can you check the response just like Mark does above and find the cached template files for me? I need to know in which twig file the error happens and the line (it should be in a comment above the error line).

**Comment by mahagr** [comment]
I think the error happens in your theme:

particles/slidewhow.yaml:
```yaml
          fields:
            article.filter.categories:
              type: joomla.categories
              label: Categories
              description: Select the categories the articles should be taken from.
              overridable: false
```

What happens if you temporarily remove the above lines?
