### ISSUE TITLE
Lable image 

### ISSUE THREAD

**Issue by Alex-Indilex** [gantry/gantry5#2951]
```
yaml
_tab_content:
          label: Content
          fields:
            image:
              type: input.imagepicker
              label: Image
              description: An image field with an image picker.
              placeholder: Pick an image
            image_lable:
              type: input.imagepicker
              label: Image Label
              description: An image field with an image picker.
              placeholder: Pick an image

html.yaml
<img{{popover_image_width|raw}}{{popover_image_height|raw}} src="{{ url(particle.image)|e }}" alt="{{ particle.image_alt|e }}" class="">
 <img src="{{ url(particle.image_label)|e }}" alt="img" class="image-label">
```

Please help. Uploading a picture to the label field, but it doesn't display. The picture link is not generated
