### ISSUE TITLE
Atoms not being inserted into site

### ISSUE THREAD

**Issue by alisamii** [gantry/gantry5#330]
Tried to create a new atom to insert the TypeKit javascript in the site.

Here's the code I used:

**The YAML**
```
name: Adobe Typekit
description: Configure Adobe Typekit.
type: atom

form:
  fields:
    enabled:
      type: input.checkbox
      label: Enabled
      description: Globally enable Typekit particles.
      default: false

    kit.id:
      type: input.text
      description: Enter the Adobe Typekit ID.
      label: Adobe Typekit
```
**The Twig**
```
{% extends '@nucleus/partials/particle.html.twig' %}

{% block javascript %}
  {{ parent() }}
  {% if particle.kit.id  %}
    <script src="//use.typekit.net/{{ particle.kit.id }}.js"></script>
    <script>try{Typekit.load();}catch(e){}</script>
  {% endif %}
{% endblock %}
```
The code generates the backend element without a problem.
![screen 20shot 20on 202015-05-21 20at 2016 3a05 3a27](https://cloud.githubusercontent.com/assets/1498512/7750241/5b8c8538-ffd3-11e4-966f-791e239c1939.png)

However no code is injected in the site on the front-end.

Tried to enable the Google Analytics atom to test.

Same issue, does not get inserted into the generated front-end code.

Also, would like to know where Javascript Atoms are injected? Are they inserted in the `<head>` element or at the end of the `<body>` element?

If they are injected at the end of the `<body>` element, is there a way to add a toggle or select box to allow the end-user to choose between `<body>` element and `<head>` element?
