### ISSUE TITLE
Div outside of <div id="g-page-surround">

### ISSUE THREAD

**Issue by AbeAlpha** [gantry/gantry5#335]
Im trying to put a div on the template outside the ```<div id="g-page-surround">```
Is this possible or im doing somthing worng?

on custom.yaml:
```
layout:
  head:
    main:
      container:
        - pagecontent
    left:
      container:
        - position-left
    righ:
      container:
        - position-righ

fix:
  container:
    - position-fix
```
on page.html.twig:
```
        <div id="g-page-surround">
            {% if page_offcanvas|trim %}
            <div class="g-offcanvas-hide g-offcanvas-toggle" data-offcanvas-toggle><i class="fa fa-fw fa-bars"></i></div>
            {% endif %}
            {{ page_top|raw }}
            {{ page_layout|raw }}
            {{ page_bottom|raw }}
        </div>
		{{ page_fix|raw }}
```
css:
```
#g-head{display:flex; flex-flow:row wrap; justify-content:center;}
#g-main #g-left #g-righ, .g-container{width:100%;}
#g-left{order:1;width:20%;background-color: #fdc;}
#g-main{order:2;width:60%;background-color: #fd9;}
#g-righ{order:3;width:20%;background-color: #fd0;}
@media (max-width:913px){
#g-main{order:1;width:70%;}
#g-righ{order:2;width:30%;}
#g-left{order:3;width:100%;}}
@media (max-width:615px){
#g-main{order:1;width:100%;}
#g-left{order:2;width:100%;}
#g-righ{order:3;width:100%;}}
```

This is working for me now but not display the module position in the template. Do not like oldschool xD
```
            {{ page_bottom|raw }}
        </div>
		<div id="fix"><jdoc:include type="modules" name="fix"/></div>
```
