### ISSUE TITLE
Twig If statement is override by base outline

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#358]
I've tried to add a `select.selectize` in a particle, in the following way:

In `twig` file i have this line `<div class=" {{ particle.animation }}" > .... some code here .... </div>`

In `yaml` file i have something like this: 
```
 animation:
      type: select.selectize
      label: Image Animation
      description: Select Image Animation.
      placeholder: 'Select...'
      default: none
      selectize:
          allowEmptyOption: true
      options:
          none: None
          animation1: Animation 1
          animation2: Animation 2
```

i've also tried `{{% if particle.animation %}}` or `{{ particle.animation|default('none') }}`
or in yaml: ` default: none` ` default: "none"`

My goal is to have a class added only if that field is checked otherwise should not be added any class, or at least to add a fake class by default as i try in this example.

**Comment by JoomFX** [comment]
Hey @adi8i 

Your code is almost fine :)

I tested it with the Logo Particle and it works fine.
Here's the YAML:

```
    animation:
      type: select.selectize
      label: Image Animation
      description: Select Image Animation.
      placeholder: 'Select...'
      default: none
      options:
          none: None
          animation1: Animation 1
          animation2: Animation 2
```

And here's the Twig:

```
{% extends '@nucleus/partials/particle.html.twig' %}

{% block particle %}
<div class="{{ particle.animation }}" > .... some code here .... </div>
<a href="{{ url(particle.url)|e }}" title="{{ particle.text|e }}" rel="home" class="{{ particle.class|e }}">
    <img src="{{ url(particle.image)|e }}" alt="{{ particle.text|e }}" />
</a>
{% endblock %}
```

And the final result with the added class is in the below screenshot ;)

http://i.imgur.com/6aiUuRg.png

**Comment by adi8i** [comment]
Because is not a `input.text` where the field is empty, but a `selectize` so there will be some options to chose from, when you go to `base outline` first option will be added as default, after that you can check or uncheck how many fields you would like, because first option will still be default one, so  `if` statement in twig file will be ignored. 

![capture](https://cloud.githubusercontent.com/assets/9744973/7808038/c040b0bc-0398-11e5-844b-ad8147f01ef7.PNG)

**Comment by JoomFX** [comment]
@adi8i I don't really understand what you are trying to do.
Basically, I did a similar thing for my templates, I have an ON/OFF option for "Wow.js" and "Animate.css" so the user can choose if these should be loaded or not:

![alt](http://i.imgur.com/k83wqd3.png)

Then depending on the choice the script is loaded in the Twig.

I just do understand, do need see the whole picture of what you are trying to do

**Comment by adi8i** [comment]
In a particle, i have a field where you can select an animation to be applied to an image.
![particle](https://cloud.githubusercontent.com/assets/9744973/7808403/92e9cb00-039b-11e5-9134-8cf8faec8a91.PNG)

In yaml file i have this code, where options will be added as classes.
![twig](https://cloud.githubusercontent.com/assets/9744973/7808420/b5694840-039b-11e5-8ed3-cc5ae6c45129.PNG)

In Twig file i have this code
![3](https://cloud.githubusercontent.com/assets/9744973/7808462/114e2068-039c-11e5-9f2e-e5a3f93c10a5.PNG)

So if `Image Animation` field will be checked one `option` will be added as class, otherwise no class will be added. 

So field unchecked => no class added. 
But now if i go to `base outline` where default setting are ... , under settings tab, on that particle will be this:
![capture](https://cloud.githubusercontent.com/assets/9744973/7808521/875252f2-039c-11e5-9e6a-055ae03fd96f.PNG)

So as time as i will open base outline first option will be added as default globally, so from this point it doesn't matter if i have Image Animation field checked or unchecked because, a class will be added anyway.

**Comment by adi8i** [comment]
Is a mess here, i will try to recreate the particle.

**Comment by JoomFX** [comment]
I would just do it with an empty/fake class:

```
    animation:
      type: select.selectize
      label: Image Animation
      description: Select Image Animation.
      placeholder: 'Select...'
      default: none
      options:
          none: None
          animation1: Animation 1
          animation2: Animation 2
```

As you see in the above code, `none` is set as default. So by default the `none` class is added which does not bring any animation (you might want to call the class `g-no-animation` to prevent conflicts with other extensions). And the result from the above is:

![alt](http://i.imgur.com/JzczLl9.png)
![alt](http://i.imgur.com/sIYv5ka.png)

And the Twig is (Logo Particle for this example):

```
{% extends '@nucleus/partials/particle.html.twig' %}

{% block particle %}
<div class="{{ particle.animation }}" > .... some code here .... </div>
<a href="{{ url(particle.url)|e }}" title="{{ particle.text|e }}" rel="home" class="{{ particle.class|e }}">
    <img src="{{ url(particle.image)|e }}" alt="{{ particle.text|e }}" />
</a>
{% endblock %}
```

If you do not want to use an empty/fake class (in which I do not see anything wrong) you might want to wait for @w00fz or @mahagr  ;)
