### ISSUE TITLE
Particle name not reflected

### ISSUE THREAD

**Issue by sural98** [gantry/gantry5#387]
I have created new particles under templates\rt_callisto\custom\particles using one of the default Callisto particles.
I have changed particle names in *.yaml but the file name appears as the name of the particle instead of that in the yaml file.
What am I missing?
![particle_names](https://cloud.githubusercontent.com/assets/1849490/7864497/164c0032-056b-11e5-92da-ce6438b9853b.png)

**Comment by adi8i** [comment]
1. Yaml file
```
name: Sample Content
description: Displays Sample Content
type: particle
```

2. Twig file
```
{% extends '@nucleus/partials/particle.html.twig' %}

.........your code..........

{% endblock %}
```

And should work, i don't see any issue :)

**Comment by sural98** [comment]
**dailyimages.html.twig**
```
{% extends '@nucleus/partials/particle.html.twig' %}

{% block particle %}

	{% if particle.title %}<h2 class="g-title">{{ particle.title|raw }}</h2>{% endif %}

	<div class="g-imagegrid {{ particle.class|e }}">
		
		<div class="g-imagegrid-wrapper {{ particle.cols|e }}">
			{% for imagegriditem in particle.imagegriditems %}
			    <div class="g-imagegrid-item">
			        <a class="g-imagegrid-link" href="{{ url(imagegriditem.image)|e }}" data-rokbox data-rokbox-album="{{ particle.album|e }}"">		
	                             <img src="{{ url(imagegriditem.image)|e }}" alt="{{ imagegriditem.imagetag|e }}">
                                     {% if particle.imagetag %}<div class="g-contentlist-img-tag">{{ particle.imagetag|e }}</div>{% endif %}
				</a>
			    </div>	
			{% endfor %} 
		</div>

	</div>	

{% endblock %}
```
**dailyimages.yaml**
```
name: Daily pics
description: Show daily pics.
type: particle

form:
  fields:
    enabled:
      type: input.checkbox
      label: Enabled
      description: Globally enable icon menu particles.
      default: true

    class:
      type: input.selectize
      label: CSS Classes
      description: CSS class name for the particle.

    title:
      type: input.text
      label: Title
      description: Customize the title text.
      placeholder: Enter title

    cols:
      type: select.selectize
      label: Grid Column
      description: Select the grid column amount
      placeholder: 'Select...'
      default: g-imagegrid-2cols
      options:
        g-imagegrid-2cols: 2 Columns
        g-imagegrid-3cols: 3 Columns
        g-imagegrid-4cols: 4 Columns
        g-imagegrid-5cols: 5 Columns

    album:
      type: input.text
      label: Album Name
      description: Customize the album name.
      placeholder: Enter album name

    imagegriditems:
      type: collection.list
      array: true
      label: Images
      description: Create each item to appear in the content row.
      value: title
      ajax: true

      fields:
        .title:
          type: input.text
          label: Title
          skip: true        
        .image:
          type: input.imagepicker
          label: Promo Image
          description: Select desired promo image.
        .imagetag:
          type: input.text
          label: Image Tag
          description: Customize the image tag.
          placeholder: Enter image tag
```
