### ISSUE TITLE
Question: Fixed Nav

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#390]
Take a look at this video. Is an workaround, i try to do something but not sure what :D.

If navigation is fixed, i can add top value to page-surround and offcanvas so will work fine, but if i try to do like in that video will not, transition applied to g-navigation will have a delay. Any ideas?

https://www.youtube.com/watch?v=XsModdOMZcE

**Comment by w00fz** [comment]
Why do you need to add a transition there? Did you try without that line?

**Comment by w00fz** [comment]
Ok @adi8i I see now.

I added two new classnames `.g-offcanvas-opening` and `.g-offcanvas-closing`, that should help you better targeting and adding the transitions.

Basically instead of having the transition on `#g-navigation` and `.g-offcanvas-open #g-navigation`, you should add it once for `.g-offcanvas-opening, .g-offcanvas-closing` and it should do what you are trying to do.

**Comment by adi8i** [comment]
@w00fz Was the same without transition too, same delay :). I will try again tomorrow .

**Comment by gyvermac** [comment]
If you use `sticky` instead of `fixed` you don't have to had to value to page-surround and off canvas.

**Comment by w00fz** [comment]
Unfortunately position `sticky` is not very well supported by browsers. I can't wait for the day it will get implemented in all browsers properly. I hate `fixed` position, only ever causes problems :)

**Comment by gyvermac** [comment]
I use `sticky`  `-webkit-sticky` `-moz-sticky`  and it seems to work : http://interface34.fr/gantry5
Subsequent sections have to be `relative`
But I didn't check on each browser...

**Comment by adi8i** [comment]
I am not sure if 'sticky' is fully supported right now :P

**Comment by w00fz** [comment]
Badly, http://caniuse.com/#search=sticky

**Comment by adi8i** [comment]
@w00fz is still the same :)

**Comment by w00fz** [comment]
Can you share your code?

**Comment by w00fz** [comment]
I just got your code from the video :)
This works fine for me and includes a little bonus where you can use the actual offcanvas size rather than hardcoding `500px` :dancer: 

``` css
@import "dependencies";

#g-navigation {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    z-index: 100;
}

.g-offcanvas-toggle {
    z-index: 101;
}

.g-offcanvas-opening #g-navigation, .g-offcanvas-closing #g-navigation {
    transition: left 300ms ease, right 300ms ease;
}

.g-offcanvas-opening #g-navigation, .g-offcanvas-open #g-navigation {
    left: $offcanvas-width;
}

.g-offcanvas-closing #g-navigation {
    left: 0;
}
```
