### ISSUE TITLE
Extend "collection.list" YAML Field

### ISSUE THREAD

**Issue by federone** [gantry/gantry5#395]
Hi,

currently "collection.list" field type is not defined and user can add unlimited field types:
![current_1](https://cloud.githubusercontent.com/assets/1756964/7899531/97af9846-0737-11e5-9ab0-80a03cf264e0.png)
Its YAML code is like this:
```javascript
items:
  type: collection.list
  array: true
  label: Info
  description: Fill Info item to display.
  value: name
  ajax: true

  fields:

	.name:
	  type: input.text
	  label: Name
	  skip: true

	.surname:
	  type: select.selectize
	  label: Surname
	  default: true
	  options:
		false: Disable
		true: Enable
```

it will be great if we had already defined fields, where user can be able or not be able to remove existing or add new sub-items:

![new_2](https://cloud.githubusercontent.com/assets/1756964/7899565/03377b64-0739-11e5-8905-a951efdc17a1.png)

and its YAML code will look something like this:
```javascript
items:
      type: collection.list
      array: true
      removable: false
      newfields: false
      label: Info
      description: Fill Info item to display.
      value: name
      ajax: true

      field:

        .name:
          type: input.text
          label: Name
          skip: true

        .surname:
          type: select.selectize
		  default: true
		  options:
			  false: Disable
			  true: Enable

      field:

        .name:
          type: input.text
          label: Name
          skip: true

        .mobile:
          type: input.text
```

here i added markup:

```javascript
removable: false
newfields: false
```

you may ask, "why you need it" - 

because Particles are like a Joomla modules - where we can have Image Slideshows or image-lightbox, or other needed deep modules/plugins,
and Gantry can be as powerful as "Wordpress Visual Composer" is, and i think better than it :)

Thank you very much,
Federico

**Comment by adi8i** [comment]
Should be a way to do that, or use another input type, at base are html inputs http://www.w3schools.com/tags/tag_input.asp . I can't tell you more right now, because i have to try this first :).

**Comment by federone** [comment]
hi,

>  or use another input type, at base are html inputs http://www.w3schools.com/tags/tag_input.asp .

i guess you dont understand me :) i'm not trying to have "form field" in particle, this code which i provided (first name, last name) is just for demonstration, so you could easily understand what i mean.

i mean to have defined (which i will define in YAML) fields, where user on backend couldn't be able to remove those fields, or add new fields.

by having such feature, i can create/integrate slideshows/lightboxes and so on. Those slideshows are very dynamic, which have sub-options, thats why i want sub-fields to be not "removable".

Best Regards

**Comment by w00fz** [comment]
Alright @federone I implemented this functionality and extended it even more. Now you have 3 options: `deletion`, `reorder` and `add_new`, they are all `true` by default and you can change them to `false` individually.

#### Example

``` yaml
...
items:
      type: collection.list
      array: true
      label: My Collection
      description: Description for my Collection.
      value: name
      ajax: true
      deletion: false   # note here
      reorder: false    # note here
      add_new: false    # note here

      fields:
        .name:
          type: input.text
          label: Name
          skip: true
          ...
```

Enjoy!
