### ISSUE TITLE
Question about collection.list

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#421]
`collection.list` seems not to work in `blueprints/styles`, will return 404 eror when click any item. 

![capture](https://cloud.githubusercontent.com/assets/9744973/8019801/d6bc1e1a-0c69-11e5-804e-d7df443220d3.PNG)

Could default items be added where the main code is, in my case `blueprints/styles/my-file.yaml` ?
(i know where to add default values, but i am asking if can add them also here, together with this code)

```
dropdown:
      type: collection.list
      label: Dropdown
      ajax: true
      array: true
      value: title
      reorder: false
      add_new: false
      deletion: false

      fields:
        .icon:
          type: input.icon
          label: Icon

// How should i add default items? //  
    title: item 1
    title: item 2
```

Or may be some `types` are used only for particles and not for styles?
