### ISSUE TITLE
Yaml Layout Preset

### ISSUE THREAD

**Issue by adi8i** [gantry/gantry5#437]
Here is the code from `default` layout preset, i've removed some sections because are irrelevant:

```
preset:
  image: gantry-admin://images/layouts/default.png
  
layout:
  header:
    container:
      - [particle-logo 30, position-header 70]

  navigation:
    container:
      - particle-menu
```

On admin will render like this:
![1](https://cloud.githubusercontent.com/assets/9744973/8052866/18561b60-0e94-11e5-87df-b5de544310ae.PNG)

Now if you remove `preset` from file, so the code will look like this:
```
layout:
  header:
    container:
      - [particle-logo 30, position-header 70]

  navigation:
    container:
      - particle-menu
```

On admin, will render this:
![2](https://cloud.githubusercontent.com/assets/9744973/8052891/523620d2-0e94-11e5-8a1d-88de7d782d9d.PNG)

Good part, you have global config for full/boxed width lol.
But on front end will render like you can see in the pic bellow, so sections (navigation, header etc) will render inside `g-container` and the website will be boxed because of the container width.
![capture](https://cloud.githubusercontent.com/assets/9744973/8052908/81003a7e-0e94-11e5-8bb3-3c0770201411.PNG)
![44](https://cloud.githubusercontent.com/assets/9744973/8052935/cb4e17ea-0e94-11e5-9516-a0aa614eea20.PNG)

So how this should work?
