### ISSUE TITLE
"Universal" YAML Layout

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#439]
@mahagr we already discussed it in https://github.com/gantry/gantry5/issues/213 where you said:

"*I wouldn't have just a single universal layout, mostly because of the more positions we add, the slower the site will get. So I'd rather have a few different layouts to choose from and the particles being copied over when you change the preset layout.*"

But I'd like to bring this up again.
There were already several users in the chat (about 10 so far) who asked how to add a new Section in the layout. And since it is not an easy task once the Template is released and uses the "Full" layout syntax I still think a "Universal" layout is actually a good idea.

I might be wrong and that's why I'd like to discuss it with you to see what the cons might be as I see only pros of having a "Universal" Layout.

So, below you will find the layout that I'm planning to use in most of my Templates. It just creates the Sections and does not bring any Module Positions by default (which, as you said, will slow the website down):

```
preset:
  image: gantry-theme://images/layouts/universal.png

layout:
  drawer:
    container:
      - []

  top:
    container:
      - []

  header:
    container:
      - [position-header-a 30, particle-menu 70]

  navigation:
    container:
      - []

  showcase:
    container:
      - []

  feature:
    container:
      - []

  utility:
    container:
      - []

  breadcrumb:
    container:
      - []

  maintop:
    container:
      - []

  container:
    1:
      - sidebar 20:
        - []
      - mainbody 60:
        - particle-system-messages
        - []
        - pagecontent
        - []
      - sidebar 20:
        - []

  mainbottom:
    container:
      - []

  extension:
    container:
      - []

  prebottom:
    container:
      - []

  bottom:
    container:
      - []

  afterbottom:
    container:
      - []

  footer:
    container:
      - []

  copyright:
    container:
      - []

  offcanvas:
      - [particle-mobile-menu]

```

The above layout gives the option of having both Left and Right Sidebars and also gives just enough Sections above and below the MainBody.

So, what do you think about it guys :)
