### ISSUE TITLE
Missing palceholder text in the inputs in Custom CSS/JS atom

### ISSUE THREAD

**Issue by newkind** [gantry/gantry5#483]
When you place the Custom CSS/JS atom and you want to add Tag Attributes to any of the items, the placeholders are empty - not sure where to change it

![hydrogen theme gantry5 wordpress wordpress 2015-06-18 10-51-19](https://cloud.githubusercontent.com/assets/1641534/8227475/101fc0f2-15a8-11e5-80f0-1990abca4b61.jpg)

**Comment by adi8i** [comment]
In `gantry5/engines/nucleus/particles/assets.yaml`
```
.extra:
          type: collection.keyvalue
          label: Tag attributes
          exclude: ['rel', 'href', 'type']
```
Will become:

```
.extra:
          type: collection.keyvalue
          label: Tag attributes
          key_placeholder: Key (data-*, style, ...)
          value_placeholder: Value
          exclude: ['rel', 'href', 'type']
```
