### ISSUE TITLE
Add custom css field for g-grid row

### ISSUE THREAD

**Issue by DamirPecnik** [gantry/gantry5#520]
Is there a possibility to add a class next to the g-grid area would be a great feature as we can style grid rows that way ...

![2015-07-02 09 49 17](https://cloud.githubusercontent.com/assets/10489911/8472299/5b2862cc-20a0-11e5-9dbd-5ecdce5540cc.jpg)

**Comment by w00fz** [comment]
You can do this but manually. We aren't providing any visual interaction for grids in the Layout Manager.
The Layout Manager is meant to be a simple interaction for the layout but anything else that is specific and not very common, you can do manually.

If you edit the `layout.yaml` and you get to the block of the grid in question, you can add the `class` in the `attributes` entry. Then save. This will always be loaded in the Layout Manager and saved, even though you don't actually see it represented in the Layout Manager. Example:

``` yaml
id: 425ccae4-ccbe-f8b0-a57d-80df81f08244
        type: grid
        subtype: false
        title: Untitled
        attributes:
            class: 'your classes space separated' # <-- note here
        children:
          -
            id: 03034451-9634-402d-9951-dbb15f8eef1c
            type: block
            subtype: false
            title: Untitled
            [...]
```
