### ISSUE TITLE
2 sidebars + main content

### ISSUE THREAD

**Issue by mariantanase** [gantry/gantry5#538]
I have a simple scenario with 2 left-right columns. I don't understand what's wrong with this code ?

    top:
      container:
        - position-top
    
    header:
      container:
        - position-header
    
    navigation:
      container:
        - particle-menu
    
    showcase:
      container:
        - position-showcase
    
    feature:
      container:
        - position-feature
    
    container:
      1:
        - sidebar1 20:
          - position-sidebar
          - position-left
    
        - main 60:
          - position-breadcrumbs
          - system_messages
          - pagecontent
    
        - sidebar2 20:
          - position-sidebar
          - position-right
    
    mainbottom:
      container:
       - position-mainbottom
    
    footer:
      container:
        - position-footer
    
    copyright:
      container:
        - position-copyright

The layout manager screenshot:
![g5-layout](https://cloud.githubusercontent.com/assets/3976174/8545178/31c9a58e-24ac-11e5-81dd-06f2d9ff0e39.png)

The frontend screenshot:
![g5-frontend](https://cloud.githubusercontent.com/assets/3976174/8545190/4510f8c2-24ac-11e5-92ae-5bac3efea051.png)

I've notice that the width of the *g-container* inside of *g-block* cause this behaviour. How can I fix this ?
Thanks

**Comment by w00fz** [comment]
Hey Marian,
this seems to be related to #468. Out of curiosity, if you look into that issue, @adi8i is showing an example where basically the whole layout structure is now indented and resides inside a `layout` entry. Before that there is a `preset`.

This structure changed a while back to be like it, could you try making this change to your layout and see if it fixes the problem?

We have seen this issue reported already and on our testing we weren't able to reproduce it so I wonder if it's related to that.

This is how it should look like:

```yaml
preset:
  image: gantry-admin://images/layouts/3-col.png

layout:
  top:
    container:
      - position-top

  header:
    container:
      - position-header

  navigation:
    container:
      - particle-menu

  showcase:
    container:
      - position-showcase

  feature:
    container:
      - position-feature

  container:
    1:
      - sidebar1 20:
        - position-sidebar
        - position-left

      - main 60:
        - position-breadcrumbs
        - system_messages
        - pagecontent

      - sidebar2 20:
        - position-sidebar
        - position-right

  mainbottom:
    container:
     - position-mainbottom

  footer:
    container:
      - position-footer

  copyright:
    container:
      - position-copyright
```
