### ISSUE TITLE
Implement way to add wrapper divs and elements around multiple sections

### ISSUE THREAD

**Issue by kevlardev** [gantry/gantry5#548]
There needs to be a way to easily add one or more wrapper divs or elements around multiple sections. This would most likely be best achieved through the yaml syntax and does not necessarily need to be represented in the layout manager UI as it would be simply for providing divs to target with css. Some sort of line and indentation to indicate that this named line would become <div class="name"> wrapping whatever sections are contained within it, as well as possibly some custom variables that could be passed as well such as additional classnames or attributes.

**Comment by mahagr** [comment]
Same as #521

**Comment by hrakak** [comment]
I like that and it would be great if we can choose the wrapper tag between div or section tag, because if we have a section without h1-h6 headings it is better to use divs instead of section because sections needs a heading semantically ( for more about this see https://www.w3.org/wiki/HTML/Usage/Headings/Missing ) I quoted >  As a general rule, include a heading (h1-h6) as a child of each section and article element.

**Comment by mahagr** [comment]
Here is my first proposal on the file format

```yaml
layout:
  div header-wrapper:
    /header/:
      - [logo 20, position-0 80]
    /navigation/:
      - menu

  /row/ main-wrapper:
    - sidebar 20:
      - position-7
      - position-4
      - position-5
    - main 60:
      - position-2
      - position-12
      - system-messages
      - system-content
    - aside 20:
      - position-6
      - position-8
      - position-3

  /footer/:
    - [position-9 30, position-10 40, position-11 30]
    - position-14

  offcanvas:
    - mobile-menu
```

The format is almost the same as previously, but I tried to simplify it a bit. Having `/header/` means that the section has option for fullwith/boxed.
