### ISSUE TITLE
Menu Titles

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#670]
@w00fz  I'm trying to figure it out for more than an hour now but I cannot and I really do not understand why. Please read below and you will understand what I mean.....

As you know there was a discussion in the chat about the Menu Item Titles that appear when you hover over an item. The user asked that those are made optional.
I checked more than 10 of the most popular websites and none of them have Menu Item Titles. So I decided to submit a PR with this feature.

And here comes my actual question. I cannot make it work and I do not understand why. I thought I will do it for less than 5mins but.... it seems that `menu.html.twig` does not understand the variables/values from `menu.yaml`.

Here's the YAML code I use:

```
    enableTitles:
      type: select.selectize
      label: Enable Titles
      description: Enable the titles/tooltips of the Menu Items.
      default: 0
      options:
        0: No
        1: Yes
```

And here's the modification in the Twig:

```
{% if particle.enableTitles|default('0') == '1' %}title="{{ item.title|e }}"{% endif %}
```

But it doesn't work.
Please Djamil, can you tell me what I'm doing wrong? It's driving me crazy mate :)

P.S.   As you can see from my code, I think that the Menu Item Titles should be disabled by default and then if a user needs them, he can enable them from the Menu Particle.
