### ISSUE TITLE
How to override twig files (load a script on all pages)

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#69]
@w00fz @mahagr guys, this is a question based on the discussion I had with you @mahagr in the Gitter chat today.

This is really important for me to figure out.

So, I need to load a script in the `<head>` on all pages. As we spoke with you @mahagr , I need to do it in the "page_head.html.twig" file. You said that I need to use the "page_head.html.twig" file located at `ROOT/media/gantry5/engines/nucleus/twig/partials` not the other one located at `ROOT/media/gantry5/engines/nucleus/templates` . So here's what I did:

1. Created the "twig" folder in "g5_hydrogen". In the "twig" folder I created the "partials" folder.
2. Copied the "page_head.html.twig" file from `ROOT/media/gantry5/engines/nucleus/twig/partials` and pasted it in `g5_hydrogen/twig/partials`
3. Created a new "js" folder in "g5_hydrogen" and copied my script there (myscript.js)
4. Edited the "templateDetails.xml" and added the "twig" and "js" folders (so they can be installed later on).
5. Edited the "page_head.html.twig" file in `g5_hydrogen/twig/partials` and added the following code on line 19:

```
<script type="text/javascript" src="{{ url('gantry-theme://js/myscript.js') }}"></script>
```

6. Cleared the Joomla cache and refreshed but "myscript.js" was not loaded in the `<head>`. Also, there is the following code (by default) in the "page_head.html.twig" file which is also not loaded in the `<head>` :

```
<link rel="stylesheet" href="{{ url('media/jui/css/icomoon.css') }}" type="text/css" />
```

So guys, how would you do it in a RT Template? How would you load a script in the `<head>` on all pages. Would you please explain it in details? I do understand that you are very busy with much more important things :)

I managed to do it with the following steps, but this is quite different from what @mahagr advised me. In the following steps I'm using the "page_head.html.twig" from `ROOT/media/gantry5/engines/nucleus/templates` :

1. Created "engine" folder in "g5_hydrogen/custom". In the "engine" folder I created "templates" folder.
2. Copied the "page_head.html.twig" file from `ROOT/media/gantry5/engines/nucleus/templates` and pasted it in `g5_hydrogen/custom/engine/templates`
3. Created a new "js" folder in "g5_hydrogen" and copied my script there (myscript.js)
4. Edited the "templateDetails.xml" and added the "twig" and "js" folders (so they can be installed later on).
5. Edited the "page_head.html.twig" file in `g5_hydrogen/custom/engine/templates` and added the following code on line 23:

```
<script type="text/javascript" src="{{ url('gantry-theme://js/myscript.js') }}"></script>
```

Now "myscript.js" is properly loaded in the `<head>` but this is not what @mahagr advised me and I do not think it is the proper way to do it. 

Thank you in advance guys and sorry for bothering you with such request :)

**Comment by mahagr** [comment]
Umh, looks like I moved twig directory to engine, so it doesn't exist in template anymore. So try to replicate the structure inside engine. Just tested it and works.

**Comment by JoomFX** [comment]
thanks a lot for the reply @mahagr but I cannot figure it out.
could you please give me more details?

here's what I did but it doesn't work:

1. Created "engine" folder in "g5_hydrogen". In the "engine" folder I created "twig" folder. In the "twig" folder I created "partials" folder.
2. Copied the "page_head.html.twig" file from `ROOT/media/gantry5/engines/nucleus/twig/partials` and pasted it in `g5_hydrogen/engine/twig/partials`

Mate, do I really need to use the "page_head.html.twig" file from `ROOT/media/gantry5/engines/nucleus/twig/partials` ? It contains the following code which is not loaded in the `<head>` :

```
<link rel="stylesheet" href="{{ url('media/jui/css/icomoon.css') }}" type="text/css" />
```

Please, give me the exact steps. What directory structure should I have in "g5_hydrogen" and which of the two files I should use:

`ROOT/media/gantry5/engines/nucleus/twig/partials`

or

`ROOT/media/gantry5/engines/nucleus/templates`

**Comment by mahagr** [comment]
Need to test it with real installation, I'm using symbolic links for development as it saves me from building the package on every change.

PS: if you want to install git version and you know your way on git, contact me on the chat. Otherwise I need to create another installation when I have some time to do it.

**Comment by JoomFX** [comment]
Thanks again @mahagr :)
It is not an urgent issue, I'm just trying for figure out how to do different things in Gantry5... and how to do them properly!

This is something that you will need in your RT Templates as well. You will need to add some scripts on all pages, different ones for the different templates and designs. A good example is the "headroom.js" script that you use on rockettheme.com as well.

So yes, when you have time please do some tests and let me know what is the proper way to do it. Basically the questions are:

1. Which "page_head.html.twig" file should be used? The on in `ROOT/media/gantry5/engines/nucleus/twig/partials/page_head.html.twig` or the one in `ROOT/media/gantry5/engines/nucleus/templates/page_head.html.twig` ?

2. How should we override the "page_head.html.twig" file? What is the exact directory structure we should have in TEMPLATE_DIR (g5_hydrogen) ?

**Comment by w00fz** [comment]
I think this was documented at some point, taking into account your feedbacks and suggestions.
Or are there still issues with this? If not, please feel free to close the issue otherwise let us know how we can improve the docs for it.

/cc @FrugalGeek

**Comment by FrugalGeek** [comment]
Sorry for delay, we documented this here: http://docs.gantry.org/gantry5/advanced/customizing-theme-files#customizing-theme-files

**Comment by JoomFX** [comment]
Hey @FrugalGeek ,

Thanks for that.
I want to highlight two things regarding the link you pasted above:

1. It is about a slightly different topic that the one this issue is about. I mean it does not explain how to override the `page_head.html.twig` file and in particular loading a script on all pages. I know how to do it (because @w00fz explained it in the chat) but it might be helpful for other users as well.

2. The link you pasted above is regarding "adding the Image Picker to the options for each section". One of the steps is to override the `section.yaml`. The content of the `section.yaml` you have pasted in the documentation is different that the one I see, in particular the "HTML Attributes" stuff:

The one in the Documentation:

```
    extra:
      type: input.text
      label: HTML Attributes
      description: Extra HTML attributes.
      default:
```

The one I see:

```
    extra:
      type: collection.keyvalue
      label: Tag Attributes
      description: Extra Tag attributes.
      key_placeholder: Key (data-*, style, ...)
      value_placeholder: Value
      exclude: ['id', 'class']
```

Probably you've used the `section.yaml` from beta 1 or beta 2 :)
Also, if I add the input.imagepicker code to my current `section.yaml` I got an error message in the backend - *500 Internal Server Error - Oops, A YAML file cannot contain tabs as indentation at line 20 (near " ")..*

Here is my `section.yaml` file:

```
name: Section
description: Layout section.
type: section

form:
  fields:
    class:
      type: input.selectize
      label: CSS Classes
      description: Enter CSS class names.
      default:

    extra:
      type: collection.keyvalue
      label: Tag Attributes
      description: Extra Tag attributes.
      key_placeholder: Key (data-*, style, ...)
      value_placeholder: Value
      exclude: ['id', 'class']
	  
    background:
      type: input.imagepicker
      label: Background
```

If I use the exact code from the Documentation, it works.
