### ISSUE TITLE
Compiler & import-dependencies issue

### ISSUE THREAD

**Issue by DanGthatRokGallery** [gantry/gantry5#810]
I was supposed to have posted this last week and didn't get around to it :(
Here is the custom.scss used on latest Callisto version and Gantry 5.1.2:
```css
// @import "dependencies";
@import "nucleus/mixins/breakpoints";

.sprocket-features.layout-slideshow .sprocket-features-desc {
      background: linear-gradient(rgba(13, 12, 12, 0.5), rgba(98, 98, 98, 0.25));
      color: #ffffff;
}
.sprocket-features.layout-slideshow .sprocket-features-title {
      background: linear-gradient(rgba(13, 12, 12, 0.25), rgba(98, 98, 98, 0.25));
      margin: 0 0 15px;
      color: #ffffff;
      font-size: $core-font-size + 2;
      line-height: $core-line-height - 0.3;
      font-family: get-font-family($font-family-promo);
      font-weight: $font-weight-bold;
}
.sprocket-features.layout-slideshow .sprocket-features-img-container:before {
        background: none;
}    
```
All the above variables are found in  **\templates\rt_callisto\scss\configuration\_typography.scss** AND/OR in **\templates\rt_callisto\scss\callisto\_roksprocket.scss**

Without **@import "dependencies";** present this is the output viewed with my Chrome Inspection tool:

![no-import_dependencies](https://cloud.githubusercontent.com/assets/3792467/9738557/0f7e7834-561a-11e5-96c7-3e0ddb52c746.jpg)

If I then ADD **@import "dependencies";** then the output changes and I get:

![with-import_dependencies](https://cloud.githubusercontent.com/assets/3792467/9738575/2714c368-561a-11e5-8e17-f94c769083e5.jpg)
