### ISSUE TITLE
Tag Attribute in collection.list (item)

### ISSUE THREAD

**Issue by JoomFX** [gantry/gantry5#817]
@w00fz @mahagr Guys, sorry to bother you with this but would you please let me know how I can add a Tag Attribute in a `collection.list`, for each item in the collection?

Let's take the Social Particle for example. I managed to add a Tag Attribute for the whole particle but I'm not able to add a Tag Attribute for each item separately.

Here is my YAML:

```
name: Social
description: Display social buttons.
type: particle

form:
  fields:
    enabled:
      type: input.checkbox
      label: Enabled
      description: Globally enable social particles.
      default: true

    css.class:
      type: input.selectize
      label: CSS Classes
      description: CSS class name for the particle.
      default: social

    extra:
      type: collection.keyvalue
      label: Tag Attributes
      description: Extra Tag attributes.
      key_placeholder: Key (data-*, style, ...)
      value_placeholder: Value
      exclude: ['id', 'class']

    title:
      type: input.text
      label: Title
      description: Customize the title text.
      placeholder: Enter title

    target:
      type: select.selectize
      label: Target
      description: Target browser window when item is clicked.
      placeholder: 'Select...'
      default: _blank
      options:
          _parent: Self
          _blank: New Window

    items:
      type: collection.list
      array: true
      label: Social Items
      description: Create each social item to display.
      value: name
      ajax: true

      fields:

        .name:
          type: input.text
          label: Name
          skip: true

        .icon:
          type: input.icon
          label: Icon

        .text:
          type: input.text
          label: Text

        .link:
          type: input.text
          label: Link

        .extra:
          type: collection.keyvalue
          label: Tag Attributes
          description: Extra Tag attributes.
          key_placeholder: Key (data-*, style, ...)
          value_placeholder: Value
          exclude: ['id', 'class']

```

And here's the Twig:

```
{% extends '@nucleus/partials/particle.html.twig' %}

{% set attr_extra = '' %}
{% if particle.extra %}
    {% for attributes in particle.extra %}
        {% for key, value in attributes %}
            {% set attr_extra = attr_extra ~ ' ' ~ key|e ~ '="' ~ value|e('html_attr') ~ '"' %}
        {% endfor %}
    {% endfor %}
{% endif %}

{% set attr_extra_item = '' %}
{% if item.extra %}
    {% for attributes in item.extra %}
        {% for key, value in attributes %}
            {% set attr_extra_item = attr_extra_item ~ ' ' ~ key|e ~ '="' ~ value|e('html_attr') ~ '"' %}
        {% endfor %}
    {% endfor %}
{% endif %}

{% block particle %}
	{% if particle.title %}<h2 class="g-title">{{ particle.title|raw }}</h2>{% endif %}
    <div class="g-social {{ particle.css.class }}" {{ attr_extra|raw }}>
        {% for item in particle.items %}
            <a target="{{ particle.target|default('_blank')|e }}" href="{{ item.link|e }}" title="{{ item.text|e }}" {{ attr_extra_item|raw }}>
                <span class="{{ item.icon|e }}"></span>
                <span class="g-social-text">{{ item.text|e }}</span>
            </a>
        {% endfor %}
    </div>
{% endblock %}

```

Obviously, I'm doing something wrong :) The Tag Attribute for the whole Particle renders fine on the frontend, but the Tag Attribute for each item in the `collection.list` is missing, not loaded at all.
Thank you in advance!
