### ISSUE TITLE
Display Flex problem while using standard Gantry particles/sections

### ISSUE THREAD

**Issue by hennysmafter** [gantry/gantry5#845]
Dear developers and community,

It appears that I together with Ali Samii found a problem in Gantry. Below I will show how to reproduce this issue.

When you go to the G5 Admin area and go to layouts just add `4x custom html particle` in one section. This section has 'full-width' layout. All the particles(4x) have the variations `rounded box2 center` and a block size of 25%. Make use of 'lorem ipsum' in the Custom HTML section of the particles and make one text a bit larger then in the other particles.

What you will get is a structure looking like this:

```html
<div class="g-container">
  <div class="g-grid">
    <div class="g-block box2 rounded center size-25">
      <div class="g-content">
        <p class="text-left">Cras justo odio</p>
      </div>
    </div>
    <div class="g-block box2 rounded center size-25">
      <div class="g-content">
        <p class="text-left">Cras justo odio, dapibus ac facilisis in</p>
      </div>
    </div>
    <div class="g-block box2 rounded center size-25">
      <div class="g-content">
        <p class="text-left">Cras justo odio</p>
      </div>
    </div>
    <div class="g-block box2 rounded center size-25">
      <div class="g-content">
        <p class="text-left">Cras justo odio</p>
      </div>
    </div>
  </div>
</div>
```

Flex is at this moment not working because of the `.g-content` this is breaking the nesting of the flex properties. Now we can't delete this `.g-content` because it is automatically added so the only thing we can do now is create a work-around.

TEMP WORKAROUND:
Add this to your custom.scss

Don't forget that you should target a section to be on the safe side. The section in this case is "g-feature"
```scss
#g-feature .g-block {
  display: -webkit-box!important;
  display: -webkit-flex!important;
  display: -ms-flexbox!important;
  display: flex!important;
}
#g-feature .g-block .g-content{
  -webkit-box-flex: 1;
  -webkit-flex: 1;
      -ms-flex: 1;
          flex: 1;
}
```

Below I post some jsfiddle links the first one will have the problem visible and the second one will have the temp workaround in place.
http://jsfiddle.net/ooa7k1v1/1/
http://jsfiddle.net/ooa7k1v1/4/

Looking forward to comments and I am willing to help fixing.
